pub(crate) use egui;
pub(crate) use web_time::Instant;

#[path = "button-color-motion.rs"]
mod button_color_motion;

#[path = "command-palette.rs"]
pub mod command_palette;
#[path = "command-palette-file-match.rs"]
pub mod command_palette_file_match;
#[path = "command-palette-query.rs"]
pub mod command_palette_query;
#[path = "command-registry.rs"]
pub mod command_registry;
#[path = "command-score.rs"]
pub mod command_score;
pub mod commands;
pub mod conflict_banner;
#[cfg(feature = "native-host")]
pub mod controller;
#[path = "css-motion.rs"]
pub mod css_motion;
#[cfg(feature = "native-host")]
pub mod document_admission;
#[path = "editor-geometry.rs"]
pub mod editor_geometry;
#[path = "editor-gutter.rs"]
mod editor_gutter;
#[path = "editor-overlay.rs"]
pub mod editor_overlay;
#[path = "editor-paint.rs"]
mod editor_paint;
#[path = "editor-row-text.rs"]
pub mod editor_row_text;
pub mod editor_surface;
#[path = "font-families.rs"]
pub mod font_families;
#[path = "font-preview.rs"]
pub mod font_preview;
#[path = "fuzzy-match.rs"]
pub mod fuzzy_match;
pub mod icons;
#[path = "keybinding-editor.rs"]
pub mod keybinding_editor;
#[path = "keybinding-search.rs"]
pub mod keybinding_search;
pub mod keymap;
pub mod modal;
pub mod presentation;
#[path = "settings-code-controls.rs"]
pub mod settings_code_controls;
#[path = "settings-controls.rs"]
pub mod settings_controls;
#[path = "settings-owner.rs"]
pub mod settings_owner;
#[path = "settings-resources.rs"]
pub mod settings_resources;
#[path = "settings-view.rs"]
pub mod settings_view;
pub mod shell;
pub mod snapshot;
#[path = "snippet-catalog.rs"]
pub mod snippet_catalog;
#[path = "snippet-completion.rs"]
pub mod snippet_completion;
#[path = "snippet-draft.rs"]
pub mod snippet_draft;
#[path = "snippet-edit.rs"]
pub mod snippet_edit;
#[path = "snippet-editor.rs"]
pub mod snippet_editor;
#[path = "snippet-editor-state.rs"]
pub mod snippet_editor_state;
pub mod split;
#[path = "keybinding-icons.rs"]
pub(crate) mod ui_icons;

#[path = "status-chord.rs"]
pub mod status_chord;
#[path = "theme-color-picker.rs"]
pub mod theme_color_picker;
#[path = "theme-draft.rs"]
pub mod theme_draft;
#[path = "theme-edit.rs"]
pub mod theme_edit;
#[path = "theme-editor.rs"]
pub mod theme_editor;
#[path = "theme-editor-tokens.rs"]
pub mod theme_editor_tokens;
#[path = "theme-live-preview.rs"]
pub mod theme_live_preview;
pub mod toast;
#[path = "tooltip-trigger.rs"]
pub mod tooltip_trigger;
pub mod tooltips;
