#[path = "auto-closing.rs"]
pub mod auto_closing;
#[path = "auto-indent.rs"]
mod auto_indent;
#[path = "bracket-navigation.rs"]
pub mod bracket_navigation;
#[path = "change-journal.rs"]
pub mod change_journal;
#[path = "cursor-commands.rs"]
pub mod cursor_commands;
pub mod decoration;
#[path = "display-layout.rs"]
pub mod display_layout;
#[path = "display-map.rs"]
pub mod display_map;
pub mod document;
pub mod editing;
pub mod find;
#[path = "find-replacement.rs"]
pub mod find_replacement;
pub mod folding;
pub mod indent;
#[path = "language-configuration.rs"]
pub mod language_configuration;
#[path = "language-typing.rs"]
pub mod language_typing;
#[path = "line-breaks.rs"]
pub mod line_breaks;
#[path = "line-commands.rs"]
pub mod line_commands;
#[path = "line-tokens.rs"]
pub mod line_tokens;
pub mod lsp;
pub mod save_cleanup;
#[path = "save-preparation.rs"]
pub mod save_preparation;
#[path = "snippet-expansion.rs"]
pub mod snippet_expansion;
#[path = "snippet-insertion.rs"]
pub mod snippet_insertion;
#[path = "snippet-normalization.rs"]
mod snippet_normalization;
#[path = "snippet-session.rs"]
pub mod snippet_session;
#[path = "snippet-syntax.rs"]
pub mod snippet_syntax;
#[path = "snippet-tracking.rs"]
pub mod snippet_tracking;
#[path = "snippet-variables.rs"]
pub mod snippet_variables;
#[path = "snippet-whitespace.rs"]
pub mod snippet_whitespace;
pub mod store;
pub mod syntax;
pub mod view;
