export const KEYMAP_CATEGORY = {
    APP: 'keymap.category.app',
    VIEW: 'keymap.category.view',
    EDITOR: 'keymap.category.editor',
    TAB: 'keymap.category.tab',
    TERMINAL: 'keymap.category.terminal',
    SEARCH: 'keymap.category.search',
    FILE: 'keymap.category.file',
    SYNC: 'keymap.category.sync',
    WINDOW: 'keymap.category.window',
    GIT: 'keymap.category.git',
    EDITOR_SUGGEST: 'keymap.category.editorSuggest',
    EDITOR_NAVIGATION: 'keymap.category.editorNavigation',
    EDITOR_SELECTION: 'keymap.category.editorSelection',
    EDITOR_LINES: 'keymap.category.editorLines',
    EDITOR_FOLDING: 'keymap.category.editorFolding',
    EDITOR_FORMAT: 'keymap.category.editorFormat',
    EDITOR_REFACTOR: 'keymap.category.editorRefactor',
    EDITOR_DISPLAY: 'keymap.category.editorDisplay',
    SHELL_COMMAND: 'keymap.category.shellCommand',
} as const
