import { KEYMAP_CATEGORY } from '@shared/lib/command-registry'

/**
 * Static catalog of monaco-editor 0.56 built-in actions TAIDE exposes as commands/keybinding rows.
 * Source: scratchpad `monaco-0.56-actions.tsv` (static scan of editor.main.js registrations).
 * `defaultBindingLabel` is a display-only mac-formatted string (chord bindings shown as two combos
 * separated by a space) — it is never parsed back into a KeyMod/KeyCode bitmask, monaco already
 * owns its own default binding.
 */
export type MonacoActionEntry = {
    actionId: string
    categoryKey: string
    defaultLabel: string
    defaultBindingLabel: string | null
}

export const MONACO_ACTIONS: MonacoActionEntry[] = [
    { actionId: 'actions.find', categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION, defaultLabel: 'Find', defaultBindingLabel: '⌘F' },
    {
        actionId: 'actions.findWithSelection',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find with Selection',
        defaultBindingLabel: '⌘E',
    },
    {
        actionId: 'codelens.showLensesInCurrentLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR,
        defaultLabel: 'Show CodeLens Commands for Current Line',
        defaultBindingLabel: null,
    },
    { actionId: 'cursorRedo', categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION, defaultLabel: 'Cursor Redo', defaultBindingLabel: null },
    { actionId: 'cursorUndo', categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION, defaultLabel: 'Cursor Undo', defaultBindingLabel: '⌘U' },
    { actionId: 'deleteAllLeft', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Delete All Left', defaultBindingLabel: '⌘⌫' },
    { actionId: 'deleteAllRight', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Delete All Right', defaultBindingLabel: '⌃K' },
    { actionId: 'deleteInsideWord', categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION, defaultLabel: 'Delete Word', defaultBindingLabel: null },
    {
        actionId: 'editor.action.addCommentLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Add Line Comment',
        defaultBindingLabel: '⌘K ⌘C',
    },
    {
        actionId: 'editor.action.addCursorsToBottom',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Cursors to Bottom',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.addCursorsToTop',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Cursors to Top',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.addSelectionToNextFindMatch',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Selection to Next Find Match',
        defaultBindingLabel: '⌘D',
    },
    {
        actionId: 'editor.action.addSelectionToPreviousFindMatch',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Selection to Previous Find Match',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.autoFix', categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR, defaultLabel: 'Auto Fix...', defaultBindingLabel: '⌥⌘.' },
    {
        actionId: 'editor.action.blockComment',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Toggle Block Comment',
        defaultBindingLabel: '⌥⇧A',
    },
    {
        actionId: 'editor.action.changeAll',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Change All Occurrences',
        defaultBindingLabel: '⌘F2',
    },
    {
        actionId: 'editor.action.changeTabDisplaySize',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Change Tab Display Size',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.clipboardCopyWithSyntaxHighlightingAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Copy with Syntax Highlighting',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.commentLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Toggle Line Comment',
        defaultBindingLabel: '⌘/',
    },
    {
        actionId: 'editor.action.copyLinesDownAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Copy Line Down',
        defaultBindingLabel: '⌥⇧↓',
    },
    {
        actionId: 'editor.action.copyLinesUpAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Copy Line Up',
        defaultBindingLabel: '⌥⇧↑',
    },
    {
        actionId: 'editor.action.decreaseHoverVerbosityLevel',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Decrease Hover Verbosity Level',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.deleteLines', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Delete Line', defaultBindingLabel: '⇧⌘K' },
    {
        actionId: 'editor.action.detectIndentation',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Detect Indentation from Content',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.duplicateSelection',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Duplicate Selection',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.fixAll', categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR, defaultLabel: 'Fix All', defaultBindingLabel: null },
    {
        actionId: 'editor.action.focusNextCursor',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Focus Next Cursor',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.focusPreviousCursor',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Focus Previous Cursor',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.fontZoomIn',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Increase Editor Font Size',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.fontZoomOut',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Decrease Editor Font Size',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.fontZoomReset',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Reset Editor Font Size',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.formatDocument',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Format Document',
        defaultBindingLabel: '⌥⇧F',
    },
    {
        actionId: 'editor.action.formatSelection',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Format Selection',
        defaultBindingLabel: '⌘K ⌘F',
    },
    {
        actionId: 'editor.action.goToImplementation',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Implementation',
        defaultBindingLabel: '⌘F12',
    },
    {
        actionId: 'editor.action.gotoLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Line/Column',
        defaultBindingLabel: '⌃G',
    },
    {
        actionId: 'editor.action.goToLocation',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Any Symbol',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.goToReferences',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to References',
        defaultBindingLabel: '⇧F12',
    },
    {
        actionId: 'editor.action.goToTypeDefinition',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Type Definition',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.hideHover', categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY, defaultLabel: 'Hide Hover', defaultBindingLabel: null },
    {
        actionId: 'editor.action.increaseHoverVerbosityLevel',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Increase Hover Verbosity Level',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.indentationToSpaces',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Convert Indentation to Spaces',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.indentationToTabs',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Convert Indentation to Tabs',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.indentLines', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Indent Line', defaultBindingLabel: '⌘]' },
    {
        actionId: 'editor.action.indentUsingSpaces',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Indent Using Spaces',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.indentUsingTabs',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Indent Using Tabs',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.inlineSuggest.toggleAlwaysShowToolbar',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SUGGEST,
        defaultLabel: 'Always Show Toolbar',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.inlineSuggest.trigger',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SUGGEST,
        defaultLabel: 'Trigger Inline Suggestion',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.inPlaceReplace.down',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Replace with Next Value',
        defaultBindingLabel: '⇧⌘.',
    },
    {
        actionId: 'editor.action.inPlaceReplace.up',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Replace with Previous Value',
        defaultBindingLabel: '⇧⌘,',
    },
    {
        actionId: 'editor.action.insertCursorAbove',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Cursor Above',
        defaultBindingLabel: '⌥⌘↑',
    },
    {
        actionId: 'editor.action.insertCursorAtEndOfEachLineSelected',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Cursors to Line Ends',
        defaultBindingLabel: '⌥⇧I',
    },
    {
        actionId: 'editor.action.insertCursorBelow',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Add Cursor Below',
        defaultBindingLabel: '⌥⌘↓',
    },
    {
        actionId: 'editor.action.insertFinalNewLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Insert Final New Line',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.insertLineAfter',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Insert Line Below',
        defaultBindingLabel: '⌘⏎',
    },
    {
        actionId: 'editor.action.insertLineBefore',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Insert Line Above',
        defaultBindingLabel: '⇧⌘⏎',
    },
    { actionId: 'editor.action.joinLines', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Join Lines', defaultBindingLabel: '⌃J' },
    {
        actionId: 'editor.action.jumpToBracket',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Bracket',
        defaultBindingLabel: '⇧⌘\\',
    },
    {
        actionId: 'editor.action.marker.next',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Next Problem (Error, Warning, Info)',
        defaultBindingLabel: '⌥F8',
    },
    {
        actionId: 'editor.action.marker.nextInFiles',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Next Problem in Files (Error, Warning, Info)',
        defaultBindingLabel: 'F8',
    },
    {
        actionId: 'editor.action.marker.prev',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Previous Problem (Error, Warning, Info)',
        defaultBindingLabel: '⌥⇧F8',
    },
    {
        actionId: 'editor.action.marker.prevInFiles',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Previous Problem in Files (Error, Warning, Info)',
        defaultBindingLabel: '⇧F8',
    },
    {
        actionId: 'editor.action.moveCarretLeftAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Move Selected Text Left',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.moveCarretRightAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Move Selected Text Right',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.moveLinesDownAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Move Line Down',
        defaultBindingLabel: '⌥↓',
    },
    {
        actionId: 'editor.action.moveLinesUpAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Move Line Up',
        defaultBindingLabel: '⌥↑',
    },
    {
        actionId: 'editor.action.moveSelectionToNextFindMatch',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Move Last Selection to Next Find Match',
        defaultBindingLabel: '⌘K ⌘D',
    },
    {
        actionId: 'editor.action.moveSelectionToPreviousFindMatch',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Move Last Selection to Previous Find Match',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.nextMatchFindAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find Next',
        defaultBindingLabel: '⌘G',
    },
    {
        actionId: 'editor.action.nextSelectionMatchFindAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find Next Selection',
        defaultBindingLabel: '⌘F3',
    },
    { actionId: 'editor.action.openLink', categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION, defaultLabel: 'Open Link', defaultBindingLabel: null },
    {
        actionId: 'editor.action.organizeImports',
        categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR,
        defaultLabel: 'Organize Imports',
        defaultBindingLabel: '⌥⇧O',
    },
    { actionId: 'editor.action.outdentLines', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Outdent Line', defaultBindingLabel: '⌘[' },
    { actionId: 'editor.action.pasteAs', categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT, defaultLabel: 'Paste As...', defaultBindingLabel: null },
    { actionId: 'editor.action.pasteAsText', categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT, defaultLabel: 'Paste as Text', defaultBindingLabel: null },
    {
        actionId: 'editor.action.peekDeclaration',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Peek Declaration',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.peekDefinition',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Peek Definition',
        defaultBindingLabel: '⌥F12',
    },
    {
        actionId: 'editor.action.peekImplementation',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Peek Implementations',
        defaultBindingLabel: '⇧⌘F12',
    },
    {
        actionId: 'editor.action.peekTypeDefinition',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Peek Type Definition',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.previousMatchFindAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find Previous',
        defaultBindingLabel: '⇧⌘G',
    },
    {
        actionId: 'editor.action.previousSelectionMatchFindAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find Previous Selection',
        defaultBindingLabel: '⇧⌘F3',
    },
    { actionId: 'editor.action.quickFix', categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR, defaultLabel: 'Quick Fix...', defaultBindingLabel: '⌘.' },
    {
        actionId: 'editor.action.quickOutline',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Symbol',
        defaultBindingLabel: '⇧⌘O',
    },
    { actionId: 'editor.action.refactor', categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR, defaultLabel: 'Refactor...', defaultBindingLabel: '⌃⇧R' },
    {
        actionId: 'editor.action.referenceSearch.trigger',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Peek References',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.reindentlines',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Reindent Lines',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.reindentselectedlines',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FORMAT,
        defaultLabel: 'Reindent Selected Lines',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.removeBrackets',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Remove Brackets',
        defaultBindingLabel: '⌥⌘⌫',
    },
    {
        actionId: 'editor.action.removeCommentLine',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Remove Line Comment',
        defaultBindingLabel: '⌘K ⌘U',
    },
    {
        actionId: 'editor.action.removeDuplicateLines',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Delete Duplicate Lines',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.action.rename', categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR, defaultLabel: 'Rename Symbol', defaultBindingLabel: 'F2' },
    {
        actionId: 'editor.action.resetSuggestSize',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SUGGEST,
        defaultLabel: 'Reset Suggest Widget Size',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.revealDeclaration',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Declaration',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.revealDefinition',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Definition',
        defaultBindingLabel: 'F12',
    },
    {
        actionId: 'editor.action.revealDefinitionAside',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Open Definition to the Side',
        defaultBindingLabel: '⌘K F12',
    },
    { actionId: 'editor.action.reverseLines', categoryKey: KEYMAP_CATEGORY.EDITOR_LINES, defaultLabel: 'Reverse lines', defaultBindingLabel: null },
    {
        actionId: 'editor.action.selectHighlights',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Select All Occurrences of Find Match',
        defaultBindingLabel: '⇧⌘L',
    },
    {
        actionId: 'editor.action.selectToBracket',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Select to Bracket',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.setSelectionAnchor',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Set Selection Anchor',
        defaultBindingLabel: '⌘K ⌘B',
    },
    {
        actionId: 'editor.action.showContextMenu',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Show Editor Context Menu',
        defaultBindingLabel: '⇧F10',
    },
    {
        actionId: 'editor.action.showDefinitionPreviewHover',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Show Definition Preview Hover',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.showHover',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Show or Focus Hover',
        defaultBindingLabel: '⌘K ⌘I',
    },
    {
        actionId: 'editor.action.showOrFocusStandaloneColorPicker',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Show or Focus Standalone Color Picker',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.smartSelect.expand',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Expand Selection',
        defaultBindingLabel: '⌃⇧⌘→',
    },
    {
        actionId: 'editor.action.smartSelect.shrink',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Shrink Selection',
        defaultBindingLabel: '⌃⇧⌘←',
    },
    {
        actionId: 'editor.action.sortLinesAscending',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Sort Lines Ascending',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.sortLinesDescending',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Sort Lines Descending',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.sourceAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_REFACTOR,
        defaultLabel: 'Source Action...',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.startFindReplaceAction',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Replace',
        defaultBindingLabel: '⌥⌘F',
    },
    {
        actionId: 'editor.action.toggleStickyScroll',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Sticky Scroll',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.toggleTabFocusMode',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Toggle Tab Key Moves Focus',
        defaultBindingLabel: '⌃⇧M',
    },
    {
        actionId: 'editor.action.transformToCamelcase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Camel Case',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToKebabcase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Kebab Case',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToLowercase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Lowercase',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToPascalcase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Pascal Case',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToSnakecase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Snake Case',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToTitlecase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Title Case',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transformToUppercase',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transform to Uppercase',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transpose',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transpose Characters around the Cursor',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.transposeLetters',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Transpose Letters',
        defaultBindingLabel: '⌃T',
    },
    {
        actionId: 'editor.action.triggerParameterHints',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SUGGEST,
        defaultLabel: 'Trigger Parameter Hints',
        defaultBindingLabel: '⇧⌘Space',
    },
    {
        actionId: 'editor.action.triggerSuggest',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SUGGEST,
        defaultLabel: 'Trigger Suggest',
        defaultBindingLabel: '⌃Space',
    },
    {
        actionId: 'editor.action.trimTrailingWhitespace',
        categoryKey: KEYMAP_CATEGORY.EDITOR_LINES,
        defaultLabel: 'Trim Trailing Whitespace',
        defaultBindingLabel: '⌘K ⌘X',
    },
    {
        actionId: 'editor.action.unicodeHighlight.disableHighlightingOfAmbiguousCharacters',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Disable highlighting of ambiguous characters',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.unicodeHighlight.disableHighlightingOfInvisibleCharacters',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Disable highlighting of invisible characters',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Disable highlighting of non basic ASCII characters',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.unicodeHighlight.showExcludeOptions',
        categoryKey: KEYMAP_CATEGORY.EDITOR_DISPLAY,
        defaultLabel: 'Show Exclude Options',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.action.wordHighlight.next',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Next Symbol Highlight',
        defaultBindingLabel: 'F7',
    },
    {
        actionId: 'editor.action.wordHighlight.prev',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Go to Previous Symbol Highlight',
        defaultBindingLabel: '⇧F7',
    },
    {
        actionId: 'editor.action.wordHighlight.trigger',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Trigger Symbol Highlight',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.actions.findWithArgs',
        categoryKey: KEYMAP_CATEGORY.EDITOR_NAVIGATION,
        defaultLabel: 'Find with Arguments',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.createFoldingRangeFromSelection',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Create Folding Range from Selection',
        defaultBindingLabel: '⌘K ⌘,',
    },
    { actionId: 'editor.fold', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Fold', defaultBindingLabel: '⌥⌘[' },
    { actionId: 'editor.foldAll', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Fold All', defaultBindingLabel: '⌘K ⌘0' },
    {
        actionId: 'editor.foldAllBlockComments',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Fold All Block Comments',
        defaultBindingLabel: '⌘K ⌘/',
    },
    {
        actionId: 'editor.foldAllExcept',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Fold All Except Selected',
        defaultBindingLabel: '⌘K ⌘-',
    },
    {
        actionId: 'editor.foldAllMarkerRegions',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Fold All Regions',
        defaultBindingLabel: '⌘K ⌘8',
    },
    {
        actionId: 'editor.foldRecursively',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Fold Recursively',
        defaultBindingLabel: '⌘K ⌘[',
    },
    {
        actionId: 'editor.gotoNextFold',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Go to Next Folding Range',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.gotoParentFold', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Go to Parent Fold', defaultBindingLabel: null },
    {
        actionId: 'editor.gotoPreviousFold',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Go to Previous Folding Range',
        defaultBindingLabel: null,
    },
    {
        actionId: 'editor.removeManualFoldingRanges',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Remove Manual Folding Ranges',
        defaultBindingLabel: '⌘K ⌘.',
    },
    { actionId: 'editor.toggleFold', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Toggle Fold', defaultBindingLabel: '⌘K ⌘L' },
    {
        actionId: 'editor.toggleFoldRecursively',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Toggle Fold Recursively',
        defaultBindingLabel: '⌘K ⇧⌘L',
    },
    {
        actionId: 'editor.toggleImportFold',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Toggle Import Fold',
        defaultBindingLabel: null,
    },
    { actionId: 'editor.unfold', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Unfold', defaultBindingLabel: '⌥⌘]' },
    { actionId: 'editor.unfoldAll', categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING, defaultLabel: 'Unfold All', defaultBindingLabel: '⌘K ⌘J' },
    {
        actionId: 'editor.unfoldAllExcept',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Unfold All Except Selected',
        defaultBindingLabel: '⌘K ⌘=',
    },
    {
        actionId: 'editor.unfoldAllMarkerRegions',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Unfold All Regions',
        defaultBindingLabel: '⌘K ⌘9',
    },
    {
        actionId: 'editor.unfoldRecursively',
        categoryKey: KEYMAP_CATEGORY.EDITOR_FOLDING,
        defaultLabel: 'Unfold Recursively',
        defaultBindingLabel: '⌘K ⌘]',
    },
    {
        actionId: 'expandLineSelection',
        categoryKey: KEYMAP_CATEGORY.EDITOR_SELECTION,
        defaultLabel: 'Expand Line Selection',
        defaultBindingLabel: '⌘L',
    },
]
