export const COLOR_NAMESPACES: readonly { id: string; tokens: readonly string[] }[] = [
    { id: 'app', tokens: ['background', 'foreground', 'border', 'focusBorder', 'shadow', 'accent'] },
    {
        id: 'appSidebar',
        tokens: [
            'background',
            'itemHover',
            'itemActive',
            'iconDefault',
            'iconAgentRunning',
            'iconAgentWorking',
            'iconAgentAwaiting',
            'iconAgentIdle',
            'iconAgentUnknown',
            'badge',
        ],
    },
    {
        id: 'tabBar',
        tokens: [
            'background',
            'tabActiveBackground',
            'tabInactiveBackground',
            'tabActiveForeground',
            'tabInactiveForeground',
            'tabBorder',
            'tabActiveIndicator',
            'dirtyDot',
            'previewForeground',
            'dropTarget',
        ],
    },
    {
        id: 'explorer',
        tokens: [
            'background',
            'itemHover',
            'itemSelected',
            'itemFocused',
            'indentGuide',
            'folderIcon',
            'gitModified',
            'gitAdded',
            'gitDeleted',
            'gitUntracked',
            'gitIgnored',
        ],
    },
    { id: 'panel', tokens: ['background', 'sectionHeader', 'inputBackground', 'inputBorder', 'matchHighlight'] },
    {
        id: 'editor',
        tokens: [
            'background',
            'foreground',
            'lineHighlight',
            'cursor',
            'selection',
            'inactiveSelection',
            'lineNumber',
            'lineNumberActive',
            'indentGuide',
            'whitespace',
            'bracketMatch',
            'findMatch',
            'findMatchHighlight',
            'hoverBackground',
            'widgetBackground',
            'widgetBorder',
        ],
    },
    { id: 'editorGutter', tokens: ['addedBackground', 'modifiedBackground', 'deletedBackground'] },
    { id: 'editorBlame', tokens: ['foreground', 'background'] },
    { id: 'diff', tokens: ['insertedBackground', 'insertedLineBackground', 'removedBackground', 'removedLineBackground', 'border'] },
    { id: 'terminal', tokens: ['background', 'foreground', 'cursor', 'selection', 'commandBlockBorder', 'linkForeground'] },
    { id: 'git', tokens: ['added', 'modified', 'deleted', 'renamed', 'untracked', 'conflicted', 'staged'] },
    {
        id: 'graph',
        tokens: [
            'lane1',
            'lane2',
            'lane3',
            'lane4',
            'lane5',
            'lane6',
            'lane7',
            'lane8',
            'lane9',
            'lane10',
            'lane11',
            'lane12',
            'refBranch',
            'refTag',
            'refHead',
        ],
    },
    { id: 'statusIndicator', tokens: ['info', 'warning', 'error', 'success'] },
    { id: 'menu', tokens: ['background', 'border', 'itemHover', 'separator'] },
    { id: 'popover', tokens: ['background', 'border', 'itemHover', 'separator'] },
    { id: 'tooltip', tokens: ['background', 'border', 'itemHover', 'separator'] },
    { id: 'modal', tokens: ['background', 'border', 'itemHover', 'separator'] },
    { id: 'scrollbar', tokens: ['thumb', 'thumbHover', 'track'] },
    { id: 'input', tokens: ['background', 'foreground', 'border', 'placeholder', 'focusBorder'] },
    { id: 'button', tokens: ['background', 'foreground', 'hoverBackground', 'primaryBackground', 'primaryForeground'] },
    { id: 'list', tokens: ['background', 'hoverBackground', 'activeBackground', 'foreground'] },
]

export const SYNTAX_TOKENS = [
    'keyword',
    'storage',
    'operator',
    'string',
    'number',
    'regexp',
    'comment',
    'docComment',
    'function',
    'method',
    'variable',
    'parameter',
    'property',
    'type',
    'class',
    'interface',
    'enum',
    'constant',
    'namespace',
    'decorator',
    'tag',
    'attribute',
    'punctuation',
    'invalid',
    'link',
    'markdownHeading',
    'markdownEmphasis',
    'markdownStrong',
    'markdownCode',
    'markdownQuote',
    'markdownListMarker',
] as const

export const SYNTAX_SCOPE_CANDIDATES: Record<(typeof SYNTAX_TOKENS)[number], string[]> = {
    keyword: ['keyword.control', 'keyword'],
    storage: ['storage.type', 'storage.modifier', 'storage'],
    operator: ['keyword.operator', 'punctuation.separator'],
    string: ['string.quoted', 'string'],
    number: ['constant.numeric'],
    regexp: ['string.regexp'],
    comment: ['comment.line', 'comment'],
    docComment: ['comment.block.documentation', 'comment'],
    function: ['entity.name.function', 'support.function'],
    method: ['entity.name.function.member', 'meta.function-call', 'entity.name.function'],
    variable: ['variable.other.readwrite', 'variable.other', 'variable'],
    parameter: ['variable.parameter'],
    property: ['variable.other.property', 'support.type.property-name', 'meta.object-literal.key'],
    type: ['support.type', 'entity.name.type'],
    class: ['entity.name.type.class', 'entity.name.class', 'support.class', 'entity.name.type'],
    interface: ['entity.name.type.interface', 'entity.name.type'],
    enum: ['entity.name.type.enum', 'entity.name.type'],
    constant: ['constant.language', 'variable.other.constant', 'constant'],
    namespace: ['entity.name.namespace', 'entity.name.type.module'],
    decorator: ['meta.decorator', 'entity.name.function.decorator', 'punctuation.decorator'],
    tag: ['entity.name.tag'],
    attribute: ['entity.other.attribute-name'],
    punctuation: ['punctuation.definition', 'punctuation'],
    invalid: ['invalid.illegal', 'invalid'],
    link: ['markup.underline.link', 'string.other.link'],
    markdownHeading: ['markup.heading'],
    markdownEmphasis: ['markup.italic'],
    markdownStrong: ['markup.bold'],
    markdownCode: ['markup.inline.raw', 'markup.raw'],
    markdownQuote: ['markup.quote'],
    markdownListMarker: ['punctuation.definition.list', 'markup.list'],
}
