import { randomUUID } from 'node:crypto'
import { execFile } from 'node:child_process'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import type { Page } from '@playwright/test'
import { buildChildProcessEnv } from './child-process-env'
import { invokeIpc } from './ipc'
import { E2E_TMP_DIR } from './paths'

const execFileAsync = promisify(execFile)

export type FixtureProject = {
    runId: string
    rootDir: string
    projectId: string
    previousActiveProjectId: string | null
}

const GREET_MODULE_CONTENT = ['export const greet = (name: string) => {', '    return `hello, ${name}`', '}', ''].join('\n')

const SHOUT_MODULE_CONTENT = ["import { greet } from './index'", '', 'export const shout = (name: string) => greet(name).toUpperCase()', ''].join(
    '\n',
)

const FIXTURE_FILES: Record<string, string> = {
    'README.md': '# taide-e2e fixture\n\nGenerated by the Playwright harness. Safe to delete.\n',
    'src/index.ts': GREET_MODULE_CONTENT,
    'src/other.ts': SHOUT_MODULE_CONTENT,
}

const GIT_COMMIT_ENV = {
    GIT_AUTHOR_NAME: 'taide-e2e',
    GIT_AUTHOR_EMAIL: 'taide-e2e@example.invalid',
    GIT_COMMITTER_NAME: 'taide-e2e',
    GIT_COMMITTER_EMAIL: 'taide-e2e@example.invalid',
}

type ProjectOpenResult = {
    project: { id: string; root: string; name: string }
    alreadyOpen: boolean
}

/**
 * Creates a throwaway git repository under `e2e/.tmp/<runId>/`, seeded with a small, deterministic
 * fixture module pair, then opens it as a TAIDE project over IPC. Every spec gets its own fresh
 * instance — this is what lets fixture-project teardown (`closeFixtureProject`) stand in for the
 * "close only the tabs/state a test created" isolation rule without per-tab bookkeeping: nothing
 * else in the app was ever using this project.
 *
 * `project_open` unconditionally switches the backend's `session.active_project` to the newly
 * opened project (`project/service.rs`), displacing whatever the user had active. This snapshots
 * that prior active project id (`null` if none) so `closeFixtureProject` can switch back to it.
 */
export const createFixtureProject = async (page: Page) => {
    const previousActiveProjectId = await invokeIpc<string | null>(page, 'project_get_active')

    const runId = randomUUID()
    const rootDir = path.join(E2E_TMP_DIR, runId)
    await mkdir(rootDir, { recursive: true })

    for (const [relativePath, content] of Object.entries(FIXTURE_FILES)) {
        const filePath = path.join(rootDir, relativePath)
        await mkdir(path.dirname(filePath), { recursive: true })
        await writeFile(filePath, content, 'utf8')
    }

    const gitEnv = buildChildProcessEnv(GIT_COMMIT_ENV)
    await execFileAsync('git', ['init', '--quiet', '--initial-branch=main'], { cwd: rootDir, env: gitEnv })
    await execFileAsync('git', ['add', '.'], { cwd: rootDir, env: gitEnv })
    await execFileAsync('git', ['-c', 'commit.gpgsign=false', 'commit', '--quiet', '-m', 'taide-e2e fixture baseline'], {
        cwd: rootDir,
        env: gitEnv,
    })

    const openResult = await invokeIpc<ProjectOpenResult>(page, 'project_open', { path: rootDir })
    return { runId, rootDir, projectId: openResult.project.id, previousActiveProjectId }
}

/**
 * Closes the fixture project and, when there was a project active before it was opened, switches
 * the backend back to it (`project_activate`) — restoring the user's own active-project selection
 * instead of leaving whatever `project_close` happened to fall back to. Both IPC calls are
 * best-effort: a closed/missing project on either end must not fail a test's cleanup.
 */
export const closeFixtureProject = async (page: Page, fixture: FixtureProject) => {
    await invokeIpc(page, 'project_close', { projectId: fixture.projectId }).catch((error: unknown) => void error)
    if (fixture.previousActiveProjectId !== null) {
        await invokeIpc(page, 'project_activate', { projectId: fixture.previousActiveProjectId }).catch((error: unknown) => void error)
    }
    await rm(fixture.rootDir, { recursive: true, force: true })
}
