import { randomUUID } from 'node:crypto'
import { execFile } from 'node:child_process'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import type { Page } from '@playwright/test'
import { buildChildProcessEnv } from './child-process-env'
import { invokeIpc } from './ipc'
import { E2E_FIXTURE_PROJECTS_DIR } from './paths'

const execFileAsync = promisify(execFile)

export type FixtureProject = {
    runId: string
    rootDir: string
    projectId: string
    previousActiveProjectId: string | null
}

const GREET_MODULE_CONTENT = ['export const greet = (name: string) => {', '    return `hello, ${name}`', '}', ''].join('\n')

const SHOUT_MODULE_CONTENT = ["import { greet } from './index'", '', 'export const shout = (name: string) => greet(name).toUpperCase()', ''].join(
    '\n',
)

/**
 * Mostly flat at the fixture root, not nested under a `src/` subdirectory — kept that way even
 * though the reason this layout originally existed no longer applies. `command-palette.tsx`'s file
 * quick-open mode used to fuzzy-filter `tree_rows` directly (`treeRowsQueryOptions`), so it could
 * only ever surface files inside a directory the Explorer tree had already expanded — a fixture
 * project starts with every directory collapsed, contradicting `docs/features/command-palette.md`
 * §3's own requirement ("트리의 lazy 로딩에 의존하면 안 된다" — must not depend on the tree's lazy
 * loading). That app defect (`docs/quality-assurance/2026-08-25-d39-e2e-pilot-run.md`) is fixed as of
 * `docs/acknowledge/2026-08-25-d42-e2e-defects-contract.md` §3, item d: quick-open now indexes the
 * whole project through a dedicated `search_list_files` walk (`projectFilesQueryOptions`),
 * independent of which tree directories happen to be expanded. The flat root layout stays regardless
 * — spec 06's `excludeGlob` assertion is written against `'other.ts'` matching at the project root,
 * and every other spec that opens a fixture file through quick-open only does so as a setup step
 * toward a different assertion (save round-trip, symbol jump, tab fan-out) a path change would
 * needlessly churn. `'src/nested-only.ts'` below is the one deliberate exception, added to give the
 * item-d fix an actual file quick-open can only find through the whole-project index, never through
 * a pre-expanded tree directory.
 */
const FIXTURE_FILES: Record<string, string> = {
    'README.md': '# taide-e2e fixture\n\nGenerated by the Playwright harness. Safe to delete.\n',
    'index.ts': GREET_MODULE_CONTENT,
    'other.ts': SHOUT_MODULE_CONTENT,
    /**
     * Without this, vtsls only ever sees the fixture as loose/inferred single files, not a project —
     * pilot run observed workspace symbol search (`#`, spec 05) never resolving at all (not even
     * slowly) against a `tsconfig.json`-less fixture. A bare directory of `.ts` files with no project
     * config is also not representative of a real TypeScript project, so this is a realistic setup
     * fix, not a workaround for a specific assertion.
     */
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'es2022', module: 'esnext', strict: true } }, null, 4) + '\n',
    'src/nested-only.ts': "export const nestedOnly = 'nested-only-marker'\n",
}

const GIT_COMMIT_ENV = {
    GIT_AUTHOR_NAME: 'taide-e2e',
    GIT_AUTHOR_EMAIL: 'taide-e2e@example.invalid',
    GIT_COMMITTER_NAME: 'taide-e2e',
    GIT_COMMITTER_EMAIL: 'taide-e2e@example.invalid',
}

type ProjectOpenResult = {
    project: { id: string; root: string; name: string }
    alreadyOpen: boolean
}

/**
 * Creates a throwaway git repository under `E2E_FIXTURE_PROJECTS_DIR/<runId>/` (OS temp dir — outside the Vite watch root, see `paths.ts`), seeded with a small, deterministic
 * fixture module pair, then opens it as a TAIDE project over IPC. Every spec gets its own fresh
 * instance — this is what lets fixture-project teardown (`closeFixtureProject`) stand in for the
 * "close only the tabs/state a test created" isolation rule without per-tab bookkeeping: nothing
 * else in the app was ever using this project.
 *
 * `project_open` unconditionally switches the backend's `session.active_project` to the newly
 * opened project (`project/service.rs`), displacing whatever the user had active. This snapshots
 * that prior active project id (`null` if none) so `closeFixtureProject` can switch back to it.
 *
 * `project_open` used to emit only `ProjectOpened`/`ProjectListChanged` (`domain/project/commands.rs`),
 * neither of which the frontend's `IpcSyncProvider` mapped to invalidating `QUERY_KEY.PROJECT.ACTIVE`
 * — every already-mounted `page` would keep rendering the previously active project (explorer tree,
 * quick-open results, etc.) for the rest of the test, since the mutation that normally covers this
 * (`useOpenProject`'s `onSuccess` invalidating `PROJECT.ALL`, `entities/project/project.query.ts`) is
 * bypassed here: this fixture calls the raw `project_open` command directly, there being no way to
 * drive Tauri's native folder picker from headless Playwright. That gap is fixed as of
 * `docs/acknowledge/2026-08-25-d42-e2e-defects-contract.md` §3, item c — `project_open` now
 * unconditionally emits `ProjectActivated` too, which `IpcSyncProvider` *does* map to a `PROJECT.ALL`
 * invalidation, so this single `project_open` call already gets the same sync a UI-driven open gets
 * for free, with no separate `project_activate` call needed below. The `heading` `waitFor` right
 * after `project_open` is this fix's own regression oracle: it only resolves once the frontend has
 * actually re-rendered with the new project's name, so it cannot pass on a build where
 * `project_open`'s `ProjectActivated` fanout silently regresses.
 */
export const createFixtureProject = async (page: Page) => {
    const previousActiveProjectId = await invokeIpc<string | null>(page, 'project_get_active')

    const runId = randomUUID()
    const rootDir = path.join(E2E_FIXTURE_PROJECTS_DIR, runId)
    await mkdir(rootDir, { recursive: true })

    for (const [relativePath, content] of Object.entries(FIXTURE_FILES)) {
        const filePath = path.join(rootDir, relativePath)
        await mkdir(path.dirname(filePath), { recursive: true })
        await writeFile(filePath, content, 'utf8')
    }

    const gitEnv = buildChildProcessEnv(GIT_COMMIT_ENV)
    await execFileAsync('git', ['init', '--quiet', '--initial-branch=main'], { cwd: rootDir, env: gitEnv })
    await execFileAsync('git', ['add', '.'], { cwd: rootDir, env: gitEnv })
    await execFileAsync('git', ['-c', 'commit.gpgsign=false', 'commit', '--quiet', '-m', 'taide-e2e fixture baseline'], {
        cwd: rootDir,
        env: gitEnv,
    })

    const openResult = await invokeIpc<ProjectOpenResult>(page, 'project_open', { path: rootDir })
    await page.getByRole('heading', { level: 2, name: openResult.project.name, exact: true }).waitFor({ state: 'visible' })

    return { runId, rootDir, projectId: openResult.project.id, previousActiveProjectId }
}

/**
 * Closes the fixture project and, when there was a project active before it was opened, switches
 * the backend back to it (`project_activate`) — restoring the user's own active-project selection
 * instead of leaving whatever `project_close` happened to fall back to. Both IPC calls are
 * best-effort: a closed/missing project on either end must not fail a test's cleanup.
 */
export const closeFixtureProject = async (page: Page, fixture: FixtureProject) => {
    await invokeIpc(page, 'project_close', { projectId: fixture.projectId }).catch((error: unknown) => void error)
    if (fixture.previousActiveProjectId !== null) {
        await invokeIpc(page, 'project_activate', { projectId: fixture.previousActiveProjectId }).catch((error: unknown) => void error)
    }
    await rm(fixture.rootDir, { recursive: true, force: true })
}
