[package]
name = "taide-runtime"
version = "0.1.0"
license = "MIT"
edition = "2021"
rust-version = "1.89"

[dependencies]
parking_lot = "0.12"
taide-infra = { path = "../taide-infra" }
taide-lsp = { path = "../taide-lsp" }
taide-model = { path = "../taide-model" }
taide-plugin = { path = "../taide-plugin" }
taide-system = { path = "../taide-system" }
taide-terminal = { path = "../taide-terminal" }
taide-tree = { path = "../taide-tree" }
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
