pub use taide_model::window::*;

pub use taide_window::service::{AUXILIARY_WINDOW_LABEL_PREFIX, AUXILIARY_WINDOW_STATE_KEY};

pub const AUXILIARY_WINDOW_DEFAULT_WIDTH: f64 = 1_000.0;
pub const AUXILIARY_WINDOW_DEFAULT_HEIGHT: f64 = 700.0;
pub const AUXILIARY_WINDOW_MIN_WIDTH: f64 = 640.0;
pub const AUXILIARY_WINDOW_MIN_HEIGHT: f64 = 420.0;
