[package]
name = "taide-model"
version = "0.1.0"
license = "MIT"
edition = "2021"
rust-version = "1.89"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = { version = "=2.0.0-rc.25", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
