use taide_model::error::{AppError, AppErrorKind, AppResult};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RemoteDenialPolicy {
    SelfAccessExpansion,
    UnreachableDesktopWindow,
    LocalFilesystemEscape,
    InstallOrProcessExecution,
    DesktopCliInterception,
    DesktopExitControl,
    SharedSingletonStateRace,
    LocalProjectHistoryExposure,
    CredentialStoreTampering,
    DesktopProcessDiagnostics,
    Unclassified,
}

impl RemoteDenialPolicy {
    pub fn denial_error(self, name: &str) -> AppError {
        let (key, fallback): (&str, String) = match self {
            RemoteDenialPolicy::SelfAccessExpansion => (
                "error.remote.deniedSelfAccessExpansion",
                format!("a remote session cannot change or extend its own remote-access permissions (password, access link): {name}"),
            ),
            RemoteDenialPolicy::UnreachableDesktopWindow => (
                "error.remote.deniedUnreachableDesktopWindow",
                format!("a remote session cannot open or control a window or app shown on the desktop's own display: {name}"),
            ),
            RemoteDenialPolicy::LocalFilesystemEscape => (
                "error.remote.deniedLocalFilesystemEscape",
                format!("a remote session cannot access an arbitrary path on the desktop's local filesystem: {name}"),
            ),
            RemoteDenialPolicy::InstallOrProcessExecution => (
                "error.remote.deniedInstallOrProcessExecution",
                format!("a remote session cannot download or run an installer: {name}"),
            ),
            RemoteDenialPolicy::DesktopCliInterception => (
                "error.remote.deniedDesktopCliInterception",
                format!("a remote session cannot change desktop CLI integration (install, hooks): {name}"),
            ),
            RemoteDenialPolicy::DesktopExitControl => (
                "error.remote.deniedDesktopExitControl",
                format!("a remote session cannot control app exit: {name}"),
            ),
            RemoteDenialPolicy::SharedSingletonStateRace => (
                "error.remote.deniedSharedSingletonStateRace",
                format!("a remote session cannot query pending external-open requests: {name}"),
            ),
            RemoteDenialPolicy::LocalProjectHistoryExposure => (
                "error.remote.deniedLocalProjectHistoryExposure",
                format!("a remote session cannot query the full project history, which is local-welcome-screen-only: {name}"),
            ),
            RemoteDenialPolicy::CredentialStoreTampering => (
                "error.remote.deniedCredentialStoreTampering",
                format!("a remote session cannot change a stored credential (AI provider token, GitHub personal access token): {name}"),
            ),
            RemoteDenialPolicy::DesktopProcessDiagnostics => (
                "error.remote.deniedDesktopProcessDiagnostics",
                format!("a remote session cannot read or reset the desktop process's performance instrumentation: {name}"),
            ),
            RemoteDenialPolicy::Unclassified => (
                "error.remote.deniedUnclassified",
                format!("a remote session cannot run a command that is not yet on the allow list: {name}"),
            ),
        };
        AppError::localized(AppErrorKind::Forbidden, key, fallback).with_arg("command", name)
    }
}

pub type RemoteDeniedCommandEntry = (&'static str, RemoteDenialPolicy);

pub const REMOTE_DENIED_COMMANDS: &[RemoteDeniedCommandEntry] = &[
    (
        "layout_move_tab_to_window",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "file_flush_complete",
        RemoteDenialPolicy::DesktopExitControl,
    ),
    ("plugin_install", RemoteDenialPolicy::LocalFilesystemEscape),
    (
        "plugin_uninstall",
        RemoteDenialPolicy::LocalFilesystemEscape,
    ),
    (
        "agent_cli_install",
        RemoteDenialPolicy::DesktopCliInterception,
    ),
    (
        "agent_cli_uninstall",
        RemoteDenialPolicy::DesktopCliInterception,
    ),
    (
        "agent_pending_external_opens",
        RemoteDenialPolicy::SharedSingletonStateRace,
    ),
    ("lsp_install", RemoteDenialPolicy::InstallOrProcessExecution),
    (
        "system_open_path",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "system_reveal_path",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "system_open_in_browser",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "system_open_app_data_path",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "system_open_external_url",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "notification_notify",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "notification_open_system_settings",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "vsix_extract_themes",
        RemoteDenialPolicy::LocalFilesystemEscape,
    ),
    (
        "vsix_import_plugin",
        RemoteDenialPolicy::LocalFilesystemEscape,
    ),
    ("remote_issue_link", RemoteDenialPolicy::SelfAccessExpansion),
    (
        "remote_set_password",
        RemoteDenialPolicy::SelfAccessExpansion,
    ),
    (
        "remote_clear_password",
        RemoteDenialPolicy::SelfAccessExpansion,
    ),
    (
        "window_set_fullscreen",
        RemoteDenialPolicy::UnreachableDesktopWindow,
    ),
    (
        "project_list_recent",
        RemoteDenialPolicy::LocalProjectHistoryExposure,
    ),
    (
        "project_forget_recent",
        RemoteDenialPolicy::LocalProjectHistoryExposure,
    ),
    ("ai_set_token", RemoteDenialPolicy::CredentialStoreTampering),
    (
        "ai_clear_token",
        RemoteDenialPolicy::CredentialStoreTampering,
    ),
    ("sync_connect", RemoteDenialPolicy::CredentialStoreTampering),
    (
        "sync_disconnect",
        RemoteDenialPolicy::CredentialStoreTampering,
    ),
    (
        "perf_snapshot",
        RemoteDenialPolicy::DesktopProcessDiagnostics,
    ),
    ("perf_reset", RemoteDenialPolicy::DesktopProcessDiagnostics),
];

pub const REMOTE_ALLOWED_COMMANDS: &[&str] = &[
    "app_get_info",
    "project_list",
    "project_get",
    "project_get_active",
    "project_open",
    "project_close",
    "project_activate",
    "project_reorder",
    "project_set_display",
    "project_group_list",
    "project_group_create",
    "project_group_rename",
    "project_group_set_color",
    "project_group_set_collapsed",
    "project_group_set_members",
    "project_group_delete",
    "project_group_reorder",
    "project_group_open",
    "project_open_in_slot",
    "shell_slot_close",
    "session_get_shell_state",
    "session_focus_shell_slot",
    "session_set_shell_slot_sizes",
    "session_set_window_chrome",
    "layout_get",
    "layout_open_tab",
    "layout_close_tab",
    "layout_activate_tab",
    "layout_move_tab",
    "layout_split",
    "layout_open_tab_in_split",
    "layout_resize",
    "layout_focus_pane",
    "layout_pin_tab",
    "layout_set_preview",
    "layout_reopen_closed",
    "layout_set_view_state",
    "layout_set_dirty",
    "layout_set_terminal_session",
    "layout_open_untitled",
    "layout_convert_untitled",
    "layout_apply_path_change",
    "layout_set_shell_view",
    "file_open",
    "file_save",
    "file_create",
    "file_rename",
    "file_delete",
    "file_copy",
    "file_mirror_dirty",
    "file_list_mirrors",
    "file_clear_mirror",
    "file_prune_mirrors",
    "file_mirror_untitled",
    "file_list_untitled_mirrors",
    "file_clear_untitled_mirror",
    "file_prune_untitled_mirrors",
    "tree_rows",
    "tree_toggle",
    "tree_collapse_all",
    "tree_reveal",
    "tree_refresh",
    "search_run",
    "search_replace",
    "search_cancel",
    "search_list_files",
    "plugin_list",
    "plugin_reload",
    "plugin_read_grammar",
    "agent_list",
    "agent_release_marker",
    "agent_cli_status",
    "agent_hooks_status",
    "agent_hooks_install",
    "agent_hooks_uninstall",
    "lsp_spawn",
    "lsp_send",
    "lsp_stop",
    "lsp_restart",
    "lsp_confirm_reinitialize",
    "lsp_report_reinitialize_failure",
    "lsp_sessions",
    "lsp_detect_servers",
    "lsp_resolve_root",
    "lsp_install_cancel",
    "git_init",
    "git_status",
    "git_diff_file",
    "git_diff_staged_text",
    "git_show_file",
    "git_log",
    "git_ahead_behind",
    "git_remotes",
    "git_gutter",
    "git_blame_range",
    "git_stage",
    "git_unstage",
    "git_discard",
    "git_commit",
    "git_push",
    "git_pull",
    "git_fetch",
    "git_current_user",
    "git_branches",
    "git_branch_create",
    "git_branch_checkout",
    "git_branch_delete",
    "git_stash_list",
    "git_stash_push",
    "git_stash_apply",
    "git_stash_drop",
    "git_discard_hunk",
    "git_undo_last_commit",
    "git_conflict_sides",
    "git_resolve_conflict",
    "git_stage_hunk",
    "git_unstage_hunk",
    "git_stage_lines",
    "git_unstage_lines",
    "git_commit_files",
    "git_file_log",
    "git_revert_commit",
    "git_tags",
    "git_tag_create",
    "git_tag_delete",
    "git_checkout_remote_branch",
    "pty_write",
    "pty_resize",
    "pty_kill",
    "pty_set_paused",
    "pty_detach",
    "terminal_sessions",
    "shell_profiles",
    "resolve_terminal_path",
    "terminal_resolve_link_candidates",
    "pty_default_options",
    "detect_tasks",
    "font_list",
    "locale_list",
    "locale_get",
    "locale_get_current",
    "theme_list",
    "theme_get",
    "theme_get_current",
    "theme_save",
    "theme_delete",
    "snippet_list",
    "snippet_save",
    "snippet_delete",
    "settings_get",
    "settings_update",
    "settings_set_theme",
    "system_usage_get",
    "system_usage_breakdown",
    "ide_get_status",
    "ide_set_selection",
    "ide_clear_selection",
    "ide_publish_diagnostics",
    "ide_resolve_diff",
    "ide_resolve_save",
    "ide_notify_at_mention",
    "ai_token_status",
    "ai_list_models",
    "ai_inline_complete",
    "ai_inline_edit",
    "ai_commit_message",
    "ai_request_cancel",
    "sync_status",
    "sync_upload",
    "sync_download",
    "remote_status",
    "remote_revoke_sessions",
    "app_file_read",
    "app_file_write",
    "pty_spawn",
    "pty_attach",
    "file_read_raw",
];

pub fn admit(name: &str) -> AppResult<()> {
    if let Some((_, policy)) = REMOTE_DENIED_COMMANDS
        .iter()
        .find(|(candidate, _)| *candidate == name)
    {
        return Err(policy.denial_error(name));
    }
    if !REMOTE_ALLOWED_COMMANDS.contains(&name) {
        return Err(RemoteDenialPolicy::Unclassified.denial_error(name));
    }
    Ok(())
}
