import type { ComponentType } from 'react'
import type { LucideProps } from 'lucide-react'
import {
    BookMarked,
    BookText,
    Box,
    Coffee,
    Cog,
    Component,
    Container,
    File,
    FileArchive,
    FileCode,
    FileCog,
    FileJson,
    FileText,
    FlaskConical,
    Folder,
    FolderCode,
    FolderOpen,
    Package,
    GitBranch,
    GitFork,
    Globe,
    Image,
    Key,
    Lock,
    Palette,
    Scale,
    Settings2,
    Terminal,
} from 'lucide-react'
import type { FileIconName } from '@shared/lib/file-icon'

export const FILE_ICON_COMPONENT_MAP: Record<FileIconName, ComponentType<LucideProps>> = {
    file: File,
    'file-code': FileCode,
    component: Component,
    'file-json': FileJson,
    'book-text': BookText,
    palette: Palette,
    globe: Globe,
    cog: Cog,
    coffee: Coffee,
    terminal: Terminal,
    'file-cog': FileCog,
    lock: Lock,
    image: Image,
    'file-text': FileText,
    'file-archive': FileArchive,
    package: Package,
    'settings-2': Settings2,
    'git-branch': GitBranch,
    'git-fork': GitFork,
    container: Container,
    'book-marked': BookMarked,
    scale: Scale,
    key: Key,
    folder: Folder,
    'folder-open': FolderOpen,
    'folder-code': FolderCode,
    box: Box,
    'flask-conical': FlaskConical,
}
