import type { ComponentType } from 'react'
import type { LucideProps } from 'lucide-react'
import {
    AppWindow,
    Banknote,
    Binary,
    BookOpen,
    Bot,
    Braces,
    Brain,
    Brush,
    Bug,
    ClipboardList,
    Cloud,
    Code,
    CodeXml,
    Container,
    Cpu,
    CreditCard,
    Database,
    Dices,
    FileText,
    FlaskConical,
    Flag,
    Folder,
    Gamepad2,
    GitBranch,
    GitFork,
    Globe,
    HardDrive,
    Heart,
    Image,
    LayoutDashboard,
    Microscope,
    Monitor,
    Network,
    Newspaper,
    NotebookPen,
    Package,
    Palette,
    PanelsTopLeft,
    PenTool,
    PiggyBank,
    Rocket,
    Server,
    Shapes,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Star,
    Swords,
    Table2,
    TabletSmartphone,
    Terminal,
    TestTube,
    Wallet,
    WandSparkles,
    Watch,
    Zap,
} from 'lucide-react'

/**
 * The project-icon catalog, in the order the picker grid draws it: development, web, mobile, data,
 * infrastructure, design, docs, testing, AI, games, finance, then general-purpose. A curated static
 * list rather than `lucide-react/dynamic`'s full set — that module's 2007 `import()` entries each
 * become their own build chunk (`docs/research/2026-09-04-batch4-topics1-5-research.md` 주제 4 §5),
 * and its `iconNames` export cannot be tree-shaken. Same shape as `file-icon-registry.ts`.
 *
 * Rust stores whichever id is chosen as an opaque `[a-z0-9-]` string and never validates it against
 * this list, deliberately: making it a Rust enum would turn *removing* one icon from this catalog
 * into a `project.json` parse failure that quarantines the whole record. Removing a name here is
 * therefore safe — {@link resolveProjectIconName} falls the stored id back to `folder`.
 */
export const PROJECT_ICON_NAMES = [
    'code',
    'code-xml',
    'terminal',
    'git-branch',
    'git-fork',
    'bug',
    'braces',
    'binary',
    'globe',
    'layout-dashboard',
    'panels-top-left',
    'monitor',
    'app-window',
    'smartphone',
    'tablet-smartphone',
    'watch',
    'database',
    'server',
    'hard-drive',
    'table-2',
    'cloud',
    'container',
    'network',
    'cpu',
    'shield-check',
    'palette',
    'brush',
    'pen-tool',
    'shapes',
    'image',
    'file-text',
    'book-open',
    'notebook-pen',
    'clipboard-list',
    'newspaper',
    'flask-conical',
    'microscope',
    'test-tube',
    'bot',
    'brain',
    'sparkles',
    'wand-sparkles',
    'gamepad-2',
    'dices',
    'swords',
    'wallet',
    'credit-card',
    'banknote',
    'piggy-bank',
    'folder',
    'rocket',
    'star',
    'heart',
    'flag',
    'zap',
    'package',
] as const

export type ProjectIconName = (typeof PROJECT_ICON_NAMES)[number]

/**
 * The icon every unresolvable name falls back to, and what a project with no icon chosen draws —
 * identical to the glyph the sidebar showed before project display existed, so the default
 * appearance is unchanged.
 */
export const DEFAULT_PROJECT_ICON_NAME = 'folder' satisfies ProjectIconName

export const PROJECT_ICON_COMPONENT_MAP: Record<ProjectIconName, ComponentType<LucideProps>> = {
    code: Code,
    'code-xml': CodeXml,
    terminal: Terminal,
    'git-branch': GitBranch,
    'git-fork': GitFork,
    bug: Bug,
    braces: Braces,
    binary: Binary,
    globe: Globe,
    'layout-dashboard': LayoutDashboard,
    'panels-top-left': PanelsTopLeft,
    monitor: Monitor,
    'app-window': AppWindow,
    smartphone: Smartphone,
    'tablet-smartphone': TabletSmartphone,
    watch: Watch,
    database: Database,
    server: Server,
    'hard-drive': HardDrive,
    'table-2': Table2,
    cloud: Cloud,
    container: Container,
    network: Network,
    cpu: Cpu,
    'shield-check': ShieldCheck,
    palette: Palette,
    brush: Brush,
    'pen-tool': PenTool,
    shapes: Shapes,
    image: Image,
    'file-text': FileText,
    'book-open': BookOpen,
    'notebook-pen': NotebookPen,
    'clipboard-list': ClipboardList,
    newspaper: Newspaper,
    'flask-conical': FlaskConical,
    microscope: Microscope,
    'test-tube': TestTube,
    bot: Bot,
    brain: Brain,
    sparkles: Sparkles,
    'wand-sparkles': WandSparkles,
    'gamepad-2': Gamepad2,
    dices: Dices,
    swords: Swords,
    wallet: Wallet,
    'credit-card': CreditCard,
    banknote: Banknote,
    'piggy-bank': PiggyBank,
    folder: Folder,
    rocket: Rocket,
    star: Star,
    heart: Heart,
    flag: Flag,
    zap: Zap,
    package: Package,
}

/**
 * `Object.hasOwn` rather than `in`: every object literal inherits `constructor`, `toString` and
 * friends, and those names pass the backend's `[a-z0-9-]` icon sanitizer — an `in` check would let
 * `constructor` resolve to `Object` and hand a non-component to the renderer.
 */
const isProjectIconName = (value: string): value is ProjectIconName => Object.hasOwn(PROJECT_ICON_COMPONENT_MAP, value)

export const resolveProjectIconName = (name: string | null | undefined) =>
    typeof name === 'string' && isProjectIconName(name) ? name : DEFAULT_PROJECT_ICON_NAME
