// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appGetInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_get_info")),
	projectList: () => typedError<ProjectRef[], AppError>(__TAURI_INVOKE("project_list")),
	projectGet: (projectId: ProjectId) => typedError<Project, AppError>(__TAURI_INVOKE("project_get", { projectId })),
	projectGetActive: () => typedError<string | null, AppError>(__TAURI_INVOKE("project_get_active")),
	projectOpen: (path: string) => typedError<ProjectOpenResult, AppError>(__TAURI_INVOKE("project_open", { path })),
	/**
	 *  Closes `project_id` and reaps every resource that only makes sense while the project is open.
	 *  See `architecture.md` §6.3 for the authoritative list of what a project close must reclaim.
	 *  `asset://` read access needs no entry of its own in that list any more: `infra::asset_protocol`
	 *  decides per-request from `state.projects`, and the `*state.projects.write() = projects;` above
	 *  (via `service::close_project`, which removes `project_id`) already revokes it before this
	 *  function's other reaps even run. Two of those other reaps are correctness-sensitive, not just
	 *  cleanup:
	 * 
	 *  - **Layout**: a layout marked dirty but not yet caught by `flush_dirty_layouts`'s periodic
	 *    2-second timer would otherwise be discarded unsaved — the `state.layouts.write().remove`
	 *    below drops the in-memory copy, and the periodic flusher's next pass over `dirty_layouts`
	 *    would then find nothing left in `state.layouts` for this `project_id` and silently skip it
	 *    (see that function's `filter_map`, which also `log::warn!`s on exactly this miss as a safety
	 *    net for any other path that removes a layout without flushing first). Flushing synchronously
	 *    here, before the removal, closes that window.
	 *  - **Terminals**: `TerminalStore::kill_project` reaps every pty session scoped to this project.
	 *    Before this, nothing called `pty_kill` for a closing project's sessions — they kept running,
	 *    attached to nothing, until the whole app quit (`TerminalStore::kill_all`).
	 * 
	 *  `GitStore`/`TreeStore` removal below is plain cache eviction (no correctness risk either way —
	 *  `resolve_repo_root`/`ensure_entry` transparently rebuild a missing entry on next access) but
	 *  still matters: without it, reopening the same folder resurrects a possibly-stale repo root or
	 *  directory listing instead of resolving fresh, and the entry otherwise sits in memory for the
	 *  rest of the app's lifetime regardless of whether the project ever reopens.
	 */
	projectClose: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("project_close", { projectId })),
	projectActivate: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("project_activate", { projectId })),
	projectReorder: (ids: ProjectId[]) => typedError<null, AppError>(__TAURI_INVOKE("project_reorder", { ids })),
	layoutGet: (projectId: ProjectId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_get", { projectId })),
	layoutOpenTab: (projectId: ProjectId, kind: TabKind, title: string, target: string | null, preview: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_open_tab", { projectId, kind, title, target, preview })),
	layoutCloseTab: (tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_close_tab", { tabId })),
	layoutActivateTab: (tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_activate_tab", { tabId })),
	layoutMoveTab: (tabId: TabId, paneId: PaneId, index: number) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_move_tab", { tabId, paneId, index })),
	layoutSplit: (paneId: PaneId, edge: DropEdge, tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_split", { paneId, edge, tabId })),
	layoutResize: (paneId: PaneId, sizes: (number | null)[]) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_resize", { paneId, sizes })),
	layoutFocusPane: (paneId: PaneId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_focus_pane", { paneId })),
	layoutPinTab: (tabId: TabId, pinned: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_pin_tab", { tabId, pinned })),
	layoutSetPreview: (tabId: TabId, preview: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_preview", { tabId, preview })),
	layoutReopenClosed: (projectId: ProjectId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_reopen_closed", { projectId })),
	layoutSetViewState: (tabId: TabId, viewState: string | null) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_view_state", { tabId, viewState })),
	layoutSetDirty: (tabId: TabId, dirty: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_dirty", { tabId, dirty })),
	layoutSetTerminalSession: (tabId: TabId, sessionId: string) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_terminal_session", { tabId, sessionId })),
	layoutOpenUntitled: (projectId: ProjectId, target: string | null) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_open_untitled", { projectId, target })),
	layoutConvertUntitled: (tabId: TabId, path: string) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_convert_untitled", { tabId, path })),
	/**
	 *  Moves a tab to the main window, an already-open auxiliary window, or a brand-new one —
	 *  "Move into New Window"/"Move back to Main Window" (contract §3.2). `NewAuxiliary` reserves a
	 *  slot and opens the real OS window *before* touching the layout, so a window-creation failure
	 *  never leaves the layout half-mutated; if the subsequent move somehow fails anyway (unreachable
	 *  in practice, since the tab was already located above), `layout::service::move_tab_to_new_window`
	 *  itself rolls back the just-inserted empty window entry, and this command additionally closes the
	 *  now-pointless OS window it just opened.
	 */
	layoutMoveTabToWindow: (tabId: TabId, target: TabWindowTarget) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_move_tab_to_window", { tabId, target })),
	layoutSetShellView: (projectId: ProjectId, patch: ShellViewPatch) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_shell_view", { projectId, patch })),
	fileOpen: (path: string) => typedError<OpenedFile, AppError>(__TAURI_INVOKE("file_open", { path })),
	fileSave: (path: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("file_save", { path, content })),
	fileCreate: (path: string, isDir: boolean) => typedError<null, AppError>(__TAURI_INVOKE("file_create", { path, isDir })),
	fileRename: (from: string, to: string) => typedError<null, AppError>(__TAURI_INVOKE("file_rename", { from, to })),
	fileDelete: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("file_delete", { path })),
	fileCopy: (from: string, to: string) => typedError<null, AppError>(__TAURI_INVOKE("file_copy", { from, to })),
	/**
	 *  Not guarded by `AppState::begin_mutation` — this command only reads `state.projects` (an
	 *  `RwLock` read, not the mutation lock) to resolve the project root; it never touches `AppState`
	 *  itself, and `persist::write_atomic`'s UUID temp-file + rename (`persist.rs`) already serializes
	 *  concurrent writers to the same mirror file (last writer wins, atomically), the same rationale
	 *  `lsp_send` (`lsp/commands.rs`) uses to skip the lock. Frequency is the practical reason this
	 *  matters: this fires on a 500ms debounce timer while the user types, far more often than
	 *  saves/git operations, so gating it behind the global mutation lock would queue every keystroke's
	 *  mirror write behind unrelated long-held mutations for no correctness benefit — ordering relative
	 *  to `file_save`'s own `clear_mirror` is guaranteed by the frontend's save-epoch guard
	 *  (`editor-pane.tsx`'s `persistMirror`), not by lock ordering. The real cost of keeping the lock
	 *  here would surface at shutdown: `handle_close_requested`'s hot-exit flush would then wait behind
	 *  a long lock holder (e.g. `git_push`) and blow through `HOT_EXIT_FLUSH_TIMEOUT_MS`, losing every
	 *  unflushed mirror instead of writing it — the opposite of what hot exit exists for.
	 */
	fileMirrorDirty: (projectId: ProjectId, path: string, content: string) => typedError<number | null, AppError>(__TAURI_INVOKE("file_mirror_dirty", { projectId, path, content })),
	fileListMirrors: (projectId: ProjectId) => typedError<MirrorEntry[], AppError>(__TAURI_INVOKE("file_list_mirrors", { projectId })),
	fileClearMirror: (projectId: ProjectId, path: string) => typedError<null, AppError>(__TAURI_INVOKE("file_clear_mirror", { projectId, path })),
	filePruneMirrors: (projectId: ProjectId, keepPaths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("file_prune_mirrors", { projectId, keepPaths })),
	/**
	 *  Not guarded by `AppState::begin_mutation` — same rationale as `file_mirror_dirty` above: reads
	 *  only `state.projects` to validate the project exists, never touches `AppState` otherwise, and
	 *  `persist::write_atomic` already serializes concurrent writers to the same untitled-mirror file.
	 */
	fileMirrorUntitled: (projectId: ProjectId, tabId: TabId, content: string) => typedError<null, AppError>(__TAURI_INVOKE("file_mirror_untitled", { projectId, tabId, content })),
	fileListUntitledMirrors: (projectId: ProjectId) => typedError<UntitledMirrorEntry[], AppError>(__TAURI_INVOKE("file_list_untitled_mirrors", { projectId })),
	fileClearUntitledMirror: (projectId: ProjectId, tabId: TabId) => typedError<null, AppError>(__TAURI_INVOKE("file_clear_untitled_mirror", { projectId, tabId })),
	filePruneUntitledMirrors: (projectId: ProjectId, keepTabIds: TabId[]) => typedError<null, AppError>(__TAURI_INVOKE("file_prune_untitled_mirrors", { projectId, keepTabIds })),
	/**
	 *  Confirms the calling window has finished flushing every dirty editor
	 *  model to the hot-exit mirror in response to `HotExitFlushRequested`, then
	 *  resumes the app exit that the main window's `CloseRequested` deferred
	 *  once every window expected to confirm has done so (Wave I: main plus any
	 *  currently-open `editor-*` auxiliary windows — see
	 *  `AppState::begin_hot_exit_flush`). A no-op if the flush was already
	 *  completed (by every window confirming, or by the timeout fallback).
	 */
	fileFlushComplete: () => typedError<null, AppError>(__TAURI_INVOKE("file_flush_complete")),
	treeRows: (projectId: ProjectId, offset: number, limit: number) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_rows", { projectId, offset, limit })),
	treeToggle: (projectId: ProjectId, path: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_toggle", { projectId, path })),
	treeReveal: (projectId: ProjectId, path: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_reveal", { projectId, path })),
	treeRefresh: (projectId: ProjectId, dir: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_refresh", { projectId, dir })),
	searchRun: (projectId: ProjectId, sessionId: string, query: SearchQuery, onMatch: Channel<SearchMatch>) => typedError<number, AppError>(__TAURI_INVOKE("search_run", { projectId, sessionId, query, onMatch })),
	searchCancel: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("search_cancel", { sessionId })),
	/**
	 *  Reacquires `AppState::begin_mutation`'s single global lock **once per file** instead of holding
	 *  it for the whole multi-file replace — a project-wide "replace all" can touch hundreds of files,
	 *  and that one lock is shared by every other mutating command (`file_save`, `git_push`, layout
	 *  writes, ...), so holding it for the entire walk-and-rewrite would starve all of them for as long
	 *  as the replace runs. Reacquiring per file keeps each hold short while still serializing every
	 *  actual write against the rest of the app's mutations. Both the target-file resolution (the tree
	 *  walk) and each file's guarded read-modify-write run inside `spawn_blocking` — none of it runs on
	 *  the async worker thread — since `service::replace_one_file` does synchronous filesystem I/O.
	 */
	searchReplace: (projectId: ProjectId, query: SearchQuery, replacement: string, paths: string[] | null) => typedError<SearchReplaceResult, AppError>(__TAURI_INVOKE("search_replace", { projectId, query, replacement, paths })),
	pluginList: () => typedError<LoadedPlugin[], AppError>(__TAURI_INVOKE("plugin_list")),
	pluginReload: () => typedError<LoadedPlugin[], AppError>(__TAURI_INVOKE("plugin_reload")),
	pluginReadGrammar: (pluginId: string, languageId: string) => typedError<string, AppError>(__TAURI_INVOKE("plugin_read_grammar", { pluginId, languageId })),
	pluginInstall: (sourcePath: string) => typedError<LoadedPlugin, AppError>(__TAURI_INVOKE("plugin_install", { sourcePath })),
	/**
	 *  No built-in-plugin protection — every entry in `plugins_dir` is a user-installed directory
	 *  (contract §3.4: "빌트인 보호 없음 — 사용자 디렉토리만"), since TAIDE ships no bundled plugins.
	 */
	pluginUninstall: (pluginId: string) => typedError<LoadedPlugin[], AppError>(__TAURI_INVOKE("plugin_uninstall", { pluginId })),
	agentList: (projectId: ProjectId) => typedError<ProjectAgents, AppError>(__TAURI_INVOKE("agent_list", { projectId })),
	agentReleaseMarker: (marker: string) => typedError<null, AppError>(__TAURI_INVOKE("agent_release_marker", { marker })),
	agentCliStatus: () => typedError<CliInstallStatus, AppError>(__TAURI_INVOKE("agent_cli_status")),
	agentHooksStatus: (projectId: ProjectId, agentName: string) => typedError<AgentHooksStatus, AppError>(__TAURI_INVOKE("agent_hooks_status", { projectId, agentName })),
	agentHooksInstall: (projectId: ProjectId, agentName: string) => typedError<AgentHooksStatus, AppError>(__TAURI_INVOKE("agent_hooks_install", { projectId, agentName })),
	agentHooksUninstall: (projectId: ProjectId, agentName: string) => typedError<AgentHooksStatus, AppError>(__TAURI_INVOKE("agent_hooks_uninstall", { projectId, agentName })),
	agentCliInstall: () => typedError<CliInstallStatus, AppError>(__TAURI_INVOKE("agent_cli_install")),
	agentCliUninstall: () => typedError<CliInstallStatus, AppError>(__TAURI_INVOKE("agent_cli_uninstall")),
	agentPendingExternalOpens: () => typedError<ExternalOpenRequest[], AppError>(__TAURI_INVOKE("agent_pending_external_opens")),
	/**
	 *  `request.owner` identifies the calling window (`getCurrentWindow().label` on the frontend —
	 *  `main`, `editor-<n>`, or the remote client's fixed `"remote"` label) so [`find_reusable_entry`]
	 *  only reuses a session within the same window. See the `channels` field doc on [`SessionEntry`]
	 *  for why. `request` bundles `project_id`/`server_id`/`root`/`owner` into one struct (mirroring
	 *  `pty_spawn`'s `opts`) purely to stay under `clippy::too_many_arguments`.
	 */
	lspSpawn: (request: LspSpawnRequest, onMessage: Channel<string>) => typedError<string, AppError>(__TAURI_INVOKE("lsp_spawn", { request, onMessage })),
	/**
	 *  Not guarded by `AppState::begin_mutation` — this command never touches `AppState`, and
	 *  per-session stdin writes are already serialized by `LspProcHandle`'s own
	 *  `tokio::sync::Mutex` (`infra::lsp_proc::LspProcHandle::write_message`). Gating this behind
	 *  the global mutation lock would only make LSP requests (which fire far more often than
	 *  saves/git operations) queue behind unrelated mutating commands for no correctness benefit.
	 */
	lspSend: (sessionId: string, message: string) => typedError<null, AppError>(__TAURI_INVOKE("lsp_send", { sessionId, message })),
	/**
	 *  `owner` (`getCurrentWindow().label`, same value the caller originally passed to `lsp_spawn`)
	 *  removes exactly that caller's subscriber entry from `entry.channels` — see the `channels` field
	 *  doc on [`SessionEntry`] for why this can't be left to `broadcast_message`'s send-failure pruning
	 *  alone. Root refcounting (`root`) then decides, independently, whether the whole session (process
	 *  included) gets torn down — a still-live owner keeps receiving messages from the shared session
	 *  even after some other owner's root is removed from it. **This owner-scoping is preserved
	 *  unchanged** by the guard restructuring below: the "still has remaining roots" branch still
	 *  returns early, under the guard, without ever reaching teardown.
	 * 
	 *  The guard (`AppState::begin_mutation`) is held only for the synchronous bookkeeping above and,
	 *  on the full-teardown path, for unlinking the entry from [`LspStore`] — `store.0.lock().remove`
	 *  runs *before* the guard is dropped, specifically so a concurrent `lsp_spawn`'s
	 *  `find_reusable_entry` or another `lsp_stop`/`lsp_send`'s `find_entry` can never observe this
	 *  session while [`shutdown_entry`] is mid-flight. [`shutdown_entry`] itself then runs unguarded
	 *  (see its own doc comment for why that's safe) — this is what stops LSP teardown from queuing
	 *  every other mutating command (`layout_*`, `file_save`, `lsp_spawn`) behind it for the whole
	 *  shutdown sequence, the file-open-blocks-on-LSP-teardown bug this restructuring fixes.
	 * 
	 *  Two overlapping full-teardown calls for the same `session_id` (double-invoked `lsp_stop`, e.g.
	 *  from a React effect cleanup racing a manual close) are safe by construction: whichever call's
	 *  guarded section runs first removes the entry from the store; the second call's own
	 *  `find_entry` then fails fast with `NotFound` instead of running a second redundant
	 *  `shutdown_entry` — strictly better than the previous behavior, where both calls could hold the
	 *  entry live long enough to both reach `shutdown_entry` and both harmlessly re-send
	 *  shutdown/exit/kill to the same (possibly already-dead) process. A concurrent `lsp_spawn` for the
	 *  same project/server/owner racing this teardown *can* still lose to it (spawning a fresh session
	 *  while the old one's process is still being killed in the background) — but that window is now
	 *  bounded by however long the language server actually takes to exit (typically well under
	 *  `LSP_SHUTDOWN_TIMEOUT_MS`, per [`wait_for_process_exit`]'s polling) rather than a blind 4-second
	 *  hold, and the old process is guaranteed to be killed regardless once its `shutdown_entry` call
	 *  completes.
	 */
	lspStop: (sessionId: string, root: string | null, owner: string) => typedError<null, AppError>(__TAURI_INVOKE("lsp_stop", { sessionId, root, owner })),
	/**
	 *  Guard-restructuring mirrors [`lsp_stop`]'s: the guard covers only the synchronous `find_entry`
	 *  lookup, is dropped before the unguarded [`shutdown_entry`] await, then re-acquired for the
	 *  respawn bookkeeping. Unlike `lsp_stop`'s full-teardown path, the entry is **not** unlinked from
	 *  [`LspStore`] here — `session_id` is reused for the restarted process, so `find_entry` continues
	 *  to resolve it throughout *this* call. That does leave a narrow unguarded window where a
	 *  concurrent `lsp_stop` for this same `session_id` can also observe the entry (still in the
	 *  store) and run its own full teardown — including unlinking it from `LspStore` — while this
	 *  call's `shutdown_entry` is also in flight against the identical `Arc<SessionEntry>` (harmless:
	 *  both converge on the same stopping/kill/`Stopped` end state). The respawn below re-checks the
	 *  store for `session_id` before installing the freshly spawned process specifically to catch that
	 *  case: if `lsp_stop` won the race and already removed the entry, spawning anyway would leak an
	 *  unreachable process no `session_id` could ever `lsp_stop`/`lsp_send` again (the old code
	 *  couldn't hit this — `begin_mutation`'s single guard spanned each call's *entire* body, so
	 *  `lsp_stop` and `lsp_restart` could never interleave at all).
	 */
	lspRestart: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("lsp_restart", { sessionId })),
	lspSessions: (projectId: ProjectId) => typedError<LspSessionInfo[], AppError>(__TAURI_INVOKE("lsp_sessions", { projectId })),
	lspDetectServers: () => typedError<LspServerDetection[], AppError>(__TAURI_INVOKE("lsp_detect_servers")),
	lspResolveRoot: (serverId: LspServerId, filePath: string) => typedError<string | null, AppError>(__TAURI_INVOKE("lsp_resolve_root", { serverId, filePath })),
	lspInstall: (serverId: LspServerId) => typedError<null, AppError>(__TAURI_INVOKE("lsp_install", { serverId })),
	lspInstallCancel: (serverId: LspServerId) => typedError<null, AppError>(__TAURI_INVOKE("lsp_install_cancel", { serverId })),
	gitInit: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_init", { projectId })),
	gitStatus: (projectId: ProjectId) => typedError<GitStatus, AppError>(__TAURI_INVOKE("git_status", { projectId })),
	gitDiffFile: (projectId: ProjectId, path: string, mode: DiffMode) => typedError<DiffSides, AppError>(__TAURI_INVOKE("git_diff_file", { projectId, path, mode })),
	gitDiffStagedText: (projectId: ProjectId) => typedError<StagedDiffText, AppError>(__TAURI_INVOKE("git_diff_staged_text", { projectId })),
	gitShowFile: (projectId: ProjectId, rev: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("git_show_file", { projectId, rev, path })),
	gitLog: (projectId: ProjectId, skip: number, take: number) => typedError<LogEntry[], AppError>(__TAURI_INVOKE("git_log", { projectId, skip, take })),
	gitAheadBehind: (projectId: ProjectId) => typedError<AheadBehind, AppError>(__TAURI_INVOKE("git_ahead_behind", { projectId })),
	gitRemotes: (projectId: ProjectId) => typedError<GitRemote[], AppError>(__TAURI_INVOKE("git_remotes", { projectId })),
	gitGutter: (projectId: ProjectId, path: string) => typedError<GutterHunk[], AppError>(__TAURI_INVOKE("git_gutter", { projectId, path })),
	gitBlameRange: (projectId: ProjectId, path: string, from: number, to: number) => typedError<BlameLine[], AppError>(__TAURI_INVOKE("git_blame_range", { projectId, path, from, to })),
	gitStage: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_stage", { projectId, paths })),
	gitUnstage: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_unstage", { projectId, paths })),
	gitDiscard: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_discard", { projectId, paths })),
	gitCommit: (projectId: ProjectId, message: string, opts: CommitOptions) => typedError<string, AppError>(__TAURI_INVOKE("git_commit", { projectId, message, opts })),
	gitPush: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_push", { projectId })),
	gitPull: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_pull", { projectId })),
	gitFetch: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_fetch", { projectId })),
	gitUndoLastCommit: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_undo_last_commit", { projectId })),
	gitBranches: (projectId: ProjectId) => typedError<GitBranch[], AppError>(__TAURI_INVOKE("git_branches", { projectId })),
	gitBranchCreate: (projectId: ProjectId, name: string, checkout: boolean) => typedError<null, AppError>(__TAURI_INVOKE("git_branch_create", { projectId, name, checkout })),
	gitBranchCheckout: (projectId: ProjectId, name: string) => typedError<null, AppError>(__TAURI_INVOKE("git_branch_checkout", { projectId, name })),
	gitBranchDelete: (projectId: ProjectId, name: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("git_branch_delete", { projectId, name, force })),
	gitStashList: (projectId: ProjectId) => typedError<GitStashEntry[], AppError>(__TAURI_INVOKE("git_stash_list", { projectId })),
	gitStashPush: (projectId: ProjectId, message: string | null) => typedError<null, AppError>(__TAURI_INVOKE("git_stash_push", { projectId, message })),
	gitStashApply: (projectId: ProjectId, index: number) => typedError<null, AppError>(__TAURI_INVOKE("git_stash_apply", { projectId, index })),
	gitStashDrop: (projectId: ProjectId, index: number) => typedError<null, AppError>(__TAURI_INVOKE("git_stash_drop", { projectId, index })),
	gitDiscardHunk: (projectId: ProjectId, path: string, hunkStart: number, hunkEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("git_discard_hunk", { projectId, path, hunkStart, hunkEnd })),
	gitCurrentUser: (projectId: ProjectId) => typedError<string | null, AppError>(__TAURI_INVOKE("git_current_user", { projectId })),
	gitConflictSides: (projectId: ProjectId, path: string) => typedError<ConflictSides, AppError>(__TAURI_INVOKE("git_conflict_sides", { projectId, path })),
	gitResolveConflict: (projectId: ProjectId, path: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("git_resolve_conflict", { projectId, path, content })),
	gitStageHunk: (projectId: ProjectId, path: string, hunkStart: number, hunkEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("git_stage_hunk", { projectId, path, hunkStart, hunkEnd })),
	gitUnstageHunk: (projectId: ProjectId, path: string, hunkStart: number, hunkEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("git_unstage_hunk", { projectId, path, hunkStart, hunkEnd })),
	gitStageLines: (projectId: ProjectId, path: string, lineStart: number, lineEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("git_stage_lines", { projectId, path, lineStart, lineEnd })),
	gitUnstageLines: (projectId: ProjectId, path: string, lineStart: number, lineEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("git_unstage_lines", { projectId, path, lineStart, lineEnd })),
	gitCommitFiles: (projectId: ProjectId, rev: string) => typedError<CommitFile[], AppError>(__TAURI_INVOKE("git_commit_files", { projectId, rev })),
	gitFileLog: (projectId: ProjectId, path: string, skip: number, take: number) => typedError<LogEntry[], AppError>(__TAURI_INVOKE("git_file_log", { projectId, path, skip, take })),
	gitRevertCommit: (projectId: ProjectId, rev: string) => typedError<RevertOutcome, AppError>(__TAURI_INVOKE("git_revert_commit", { projectId, rev })),
	gitTags: (projectId: ProjectId) => typedError<TagInfo[], AppError>(__TAURI_INVOKE("git_tags", { projectId })),
	gitTagCreate: (projectId: ProjectId, name: string, target: string, opts: TagCreateOptions) => typedError<null, AppError>(__TAURI_INVOKE("git_tag_create", { projectId, name, target, opts })),
	gitTagDelete: (projectId: ProjectId, name: string) => typedError<null, AppError>(__TAURI_INVOKE("git_tag_delete", { projectId, name })),
	gitCheckoutRemoteBranch: (projectId: ProjectId, remoteRef: string) => typedError<null, AppError>(__TAURI_INVOKE("git_checkout_remote_branch", { projectId, remoteRef })),
	ptyDefaultOptions: (projectId: ProjectId, cwd: string | null) => typedError<PtySpawnOptions, AppError>(__TAURI_INVOKE("pty_default_options", { projectId, cwd })),
	/**
	 *  Holds `TerminalStore`'s lock only long enough to clone out the session's writer handle
	 *  (`PtySession::writer_handle` — an `Arc` around the same inner `Mutex<Box<dyn Write>>`
	 *  `PtySession::write` locks, so this is not a second, independent write path), not for the write
	 *  itself. The write blocks on the child's stdin pipe, which backs up (and this call blocks with
	 *  it) whenever the child isn't reading its input — previously that blocked write held the *whole
	 *  store's* lock, so every other terminal command (`pty_resize`, `pty_kill` for this very session,
	 *  `pty_attach`/`pty_detach` for any other session, `terminal_sessions`) queued behind it until the
	 *  child drained its input or was killed by some other means, which nothing could do while
	 *  `pty_kill` itself was one of the commands stuck waiting on the same lock.
	 */
	ptyWrite: (sessionId: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("pty_write", { sessionId, data })),
	ptyResize: (sessionId: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("pty_resize", { sessionId, cols, rows })),
	ptyKill: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("pty_kill", { sessionId })),
	ptySetPaused: (sessionId: string, paused: boolean) => typedError<null, AppError>(__TAURI_INVOKE("pty_set_paused", { sessionId, paused })),
	/**
	 *  Removes exactly the subscriber `pty_attach` registered under `subscription_id` — the counterpart
	 *  that lets a still-open window stop receiving a session's output without waiting for
	 *  `broadcast_output`'s send-failure pruning (which only fires once the window itself closes). A
	 *  session or subscription that no longer exists is treated as already-detached rather than an
	 *  error, since cleanup can legitimately race a `pty_kill` for the same session.
	 */
	ptyDetach: (sessionId: string, subscriptionId: number) => typedError<null, AppError>(__TAURI_INVOKE("pty_detach", { sessionId, subscriptionId })),
	terminalSessions: (projectId: ProjectId) => typedError<TerminalSession[], AppError>(__TAURI_INVOKE("terminal_sessions", { projectId })),
	shellProfiles: () => typedError<ShellProfile[], AppError>(__TAURI_INVOKE("shell_profiles")),
	resolveTerminalPath: (path: string, cwd: string) => typedError<string, AppError>(__TAURI_INVOKE("resolve_terminal_path", { path, cwd })),
	detectTasks: (projectId: ProjectId) => typedError<Task[], AppError>(__TAURI_INVOKE("detect_tasks", { projectId })),
	fontList: () => typedError<FontFamily[], AppError>(__TAURI_INVOKE("font_list")),
	localeList: () => typedError<LocaleSummary[], AppError>(__TAURI_INVOKE("locale_list")),
	localeGet: (localeId: string) => typedError<ResolvedLocale_Serialize, AppError>(__TAURI_INVOKE("locale_get", { localeId })),
	localeGetCurrent: (systemLanguage: string) => typedError<ResolvedLocale_Serialize, AppError>(__TAURI_INVOKE("locale_get_current", { systemLanguage })),
	themeList: () => typedError<ThemeSummary[], AppError>(__TAURI_INVOKE("theme_list")),
	themeGet: (themeId: string) => typedError<ResolvedTheme_Serialize, AppError>(__TAURI_INVOKE("theme_get", { themeId })),
	themeGetCurrent: (systemTheme: string) => typedError<ResolvedTheme_Serialize, AppError>(__TAURI_INVOKE("theme_get_current", { systemTheme })),
	themeSave: (theme: Theme_Deserialize) => typedError<ThemeSummary, AppError>(__TAURI_INVOKE("theme_save", { theme })),
	themeDelete: (themeId: string) => typedError<null, AppError>(__TAURI_INVOKE("theme_delete", { themeId })),
	snippetList: () => typedError<SnippetFile_Serialize[], AppError>(__TAURI_INVOKE("snippet_list")),
	snippetSave: (fileName: string, content: string) => typedError<SnippetFile_Serialize, AppError>(__TAURI_INVOKE("snippet_save", { fileName, content })),
	snippetDelete: (fileName: string) => typedError<null, AppError>(__TAURI_INVOKE("snippet_delete", { fileName })),
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	settingsUpdate: (patch: SettingsPatch) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_update", { patch })),
	/**
	 *  Unlike `settings_update`, this also emits `ThemeChanged` — the narrower event
	 *  `ipc-sync-provider.tsx` listens for to invalidate `THEME.ALL` and actually refetch the newly
	 *  picked theme's colors, which a `SettingsChanged` alone (below, via `apply_and_broadcast`)
	 *  doesn't trigger.
	 */
	settingsSetTheme: (themeId: string) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set_theme", { themeId })),
	systemUsageGet: () => typedError<SystemUsage, AppError>(__TAURI_INVOKE("system_usage_get")),
	systemUsageBreakdown: () => typedError<SystemUsageProcess[], AppError>(__TAURI_INVOKE("system_usage_breakdown")),
	systemOpenPath: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("system_open_path", { path })),
	systemRevealPath: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("system_reveal_path", { path })),
	systemOpenInBrowser: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("system_open_in_browser", { path })),
	systemOpenAppDataPath: (kind: AppDataPathKind) => typedError<null, AppError>(__TAURI_INVOKE("system_open_app_data_path", { kind })),
	systemOpenExternalUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("system_open_external_url", { url })),
	ideGetStatus: () => typedError<IdeStatus, AppError>(__TAURI_INVOKE("ide_get_status")),
	ideStart: () => typedError<IdeStatus, AppError>(__TAURI_INVOKE("ide_start")),
	ideStop: () => typedError<null, AppError>(__TAURI_INVOKE("ide_stop")),
	ideSetSelection: (input: IdeSelectionInput) => typedError<null, AppError>(__TAURI_INVOKE("ide_set_selection", { input })),
	ideClearSelection: () => typedError<null, AppError>(__TAURI_INVOKE("ide_clear_selection")),
	idePublishDiagnostics: (projectId: ProjectId, items: IdeDiagnostic[]) => typedError<null, AppError>(__TAURI_INVOKE("ide_publish_diagnostics", { projectId, items })),
	ideResolveDiff: (requestId: string, outcome: IdeDiffOutcome, content: string | null) => typedError<null, AppError>(__TAURI_INVOKE("ide_resolve_diff", { requestId, outcome, content })),
	ideResolveSave: (requestId: string, saved: boolean) => typedError<null, AppError>(__TAURI_INVOKE("ide_resolve_save", { requestId, saved })),
	ideNotifyAtMention: (path: string, lineStart: number, lineEnd: number) => typedError<null, AppError>(__TAURI_INVOKE("ide_notify_at_mention", { path, lineStart, lineEnd })),
	aiTokenStatus: () => typedError<AiTokenStatus, AppError>(__TAURI_INVOKE("ai_token_status")),
	aiSetToken: (provider: AiProviderId, token: string) => typedError<null, AppError>(__TAURI_INVOKE("ai_set_token", { provider, token })),
	aiClearToken: (provider: AiProviderId) => typedError<null, AppError>(__TAURI_INVOKE("ai_clear_token", { provider })),
	aiListModels: (provider: AiProviderId) => typedError<AiModelInfo[], AppError>(__TAURI_INVOKE("ai_list_models", { provider })),
	aiInlineComplete: (request: AiInlineCompleteRequest) => typedError<AiInlineCompleteResponse, AppError>(__TAURI_INVOKE("ai_inline_complete", { request })),
	/**
	 *  `provider`/`model` are resolved before `request_store.begin()` — resolving after would leave a
	 *  `begin()`ed entry stranded with no matching `finish()` on a resolution failure (see
	 *  [`AiRequestStore::begin`]'s doc comment on why a stray entry blocks `requestId` reuse and leaks
	 *  its cancel sender).
	 */
	aiInlineEdit: (request: AiInlineEditRequest) => typedError<AiInlineEditResponse, AppError>(__TAURI_INVOKE("ai_inline_edit", { request })),
	/**
	 *  `provider`/`model` are resolved before `request_store.begin()` — see [`ai_inline_edit`]'s doc
	 *  comment for why.
	 */
	aiCommitMessage: (request: AiCommitMessageRequest) => typedError<AiCommitMessageResponse, AppError>(__TAURI_INVOKE("ai_commit_message", { request })),
	aiRequestCancel: (requestId: string) => typedError<null, AppError>(__TAURI_INVOKE("ai_request_cancel", { requestId })),
	syncStatus: () => typedError<SyncStatus, AppError>(__TAURI_INVOKE("sync_status")),
	syncConnect: (pat: string) => typedError<SyncStatus, AppError>(__TAURI_INVOKE("sync_connect", { pat })),
	syncDisconnect: () => typedError<SyncStatus, AppError>(__TAURI_INVOKE("sync_disconnect")),
	syncUpload: () => typedError<SyncStatus, AppError>(__TAURI_INVOKE("sync_upload")),
	syncDownload: (force: boolean) => typedError<SyncDownloadResult, AppError>(__TAURI_INVOKE("sync_download", { force })),
	vsixExtractThemes: (vsixPath: string) => typedError<VsixThemeExtractionResult, AppError>(__TAURI_INVOKE("vsix_extract_themes", { vsixPath })),
	/**
	 *  Imports a real VS Code `.vsix`'s language/grammar contributions as a new TAIDE plugin
	 *  (`service::import_vsix_as_plugin`), then reloads the plugin list the same way `plugin_install`
	 *  does so the frontend gets the freshly-installed plugin's enabled/error state immediately.
	 */
	vsixImportPlugin: (vsixPath: string) => typedError<LoadedPlugin, AppError>(__TAURI_INVOKE("vsix_import_plugin", { vsixPath })),
	remoteStatus: () => typedError<RemoteStatus, AppError>(__TAURI_INVOKE("remote_status")),
	remoteStart: () => typedError<RemoteStatus, AppError>(__TAURI_INVOKE("remote_start")),
	remoteStop: () => typedError<null, AppError>(__TAURI_INVOKE("remote_stop")),
	/**
	 *  Issues a one-time link token and formats it into a URL the user shares
	 *  with another device. When `Settings::remote_allowed_hosts` has at least
	 *  one registered tunnel hostname, the link points at that hostname over
	 *  `https` instead of the loopback address — a device reached only through
	 *  the tunnel (not on the same machine/network as the loopback bind) could
	 *  never resolve `http://127.0.0.1:{port}` (`docs/acknowledge/
	 *  2026-08-15-wave-b-hardening-contract.md` §6). The first registered host is
	 *  used; `auth_middleware`/`is_allowed_host` accept a request addressed to
	 *  *any* registered host regardless of which one the link happened to name.
	 */
	remoteIssueLink: () => typedError<RemoteLinkInfo, AppError>(__TAURI_INVOKE("remote_issue_link")),
	remoteRevokeSessions: () => typedError<null, AppError>(__TAURI_INVOKE("remote_revoke_sessions")),
	/**
	 *  Sets (or replaces) the remote-access password: hashed with a fresh salt
	 *  and stored in the OS keyring (never in `settings.json` — see
	 *  `docs/acknowledge/2026-08-14-hotexit-remote-password-contract.md` §3.2).
	 *  Every existing session is invalidated so devices authenticated under the
	 *  old password (or under no-password mode) must re-authenticate.
	 * 
	 *  The password is trimmed before both the length check and the hash (see
	 *  [`service::validate_and_trim_password`]): the settings UI already trims
	 *  client-side, so this makes the backend the single source of truth instead
	 *  of trusting that every caller does the same. `REMOTE_PASSWORD_MIN_LEN` is
	 *  only enforced here, on write — a password already stored below that
	 *  length (set before this check existed) keeps working until the user
	 *  changes it, per `docs/acknowledge/2026-08-15-wave-b-hardening-contract.md`
	 *  §3.1. The login form itself deliberately does *not* trim (see
	 *  `server.rs`'s `login_post_route`) since the stored value is already
	 *  trimmed.
	 */
	remoteSetPassword: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("remote_set_password", { password })),
	/**
	 *  Removes the remote-access password, reverting to link-only access
	 *  (backward-compatible legacy mode). Invalidates every existing session.
	 */
	remoteClearPassword: () => typedError<null, AppError>(__TAURI_INVOKE("remote_clear_password")),
	windowOpenAuxiliary: (projectId: ProjectId, windowSlot: number) => typedError<AuxiliaryWindowInfo, AppError>(__TAURI_INVOKE("window_open_auxiliary", { projectId, windowSlot })),
	/**
	 *  Toggles Zen mode's optional fullscreen (`Settings::zen_fullscreen`) for the calling window —
	 *  `window: tauri::Window` is Tauri-injected as whichever window's webview made this IPC call
	 *  (same pattern as `file::commands::file_flush_complete`), so the frontend never needs to name its
	 *  own label and can't fullscreen a window that isn't itself. A plain wrapper over
	 *  `tauri::Window::set_fullscreen` — a custom app command, so (per the S1 capability audit) it
	 *  needs no `core:window:allow-set-fullscreen` ACL permission; that permission only gates the
	 *  window plugin's own JS-exposed `setFullscreen` call, not a Rust-side call made from inside a
	 *  command handler.
	 */
	windowSetFullscreen: (fullscreen: boolean) => typedError<null, AppError>(__TAURI_INVOKE("window_set_fullscreen", { fullscreen })),
	appFileRead: (target: AppFileTarget) => typedError<string, AppError>(__TAURI_INVOKE("app_file_read", { target })),
	/**
	 *  Writes an `AppFileTarget`'s content. `Settings` runs the exact same
	 *  parse→sanitize→apply→broadcast pipeline as `settings_update`/`sync_download`
	 *  (`settings::commands::apply_and_broadcast`) so a hand-edited `settings.json` reaches every
	 *  window/remote session the same way a patch-based update does; invalid JSON is rejected and the
	 *  on-disk file is left untouched. `Prompt` is a plain validate-then-write with no cross-window
	 *  broadcast, since prompt templates are only read lazily at the moment an AI request builds its
	 *  prompt (`ai::prompt::load_*`), not cached in `AppState`.
	 */
	appFileWrite: (target: AppFileTarget, content: string) => typedError<null, AppError>(__TAURI_INVOKE("app_file_write", { target, content })),
};

/** Events */
export const events = {
	agentExternalOpen: makeEvent<AgentExternalOpen>("agent:external-open"),
	agentStateChanged: makeEvent<AgentStateChanged>("agent:state-changed"),
	appHotExitFlushRequested: makeEvent<HotExitFlushRequested>("app:hot-exit-flush-requested"),
	appReady: makeEvent<AppReady>("app:ready"),
	fsChanged: makeEvent<FsChanged>("fs:changed"),
	gitRefsChanged: makeEvent<GitRefsChanged>("git:refs-changed"),
	gitStatusChanged: makeEvent<GitStatusChanged>("git:status-changed"),
	ideCloseTabRequested: makeEvent<IdeCloseTabRequested>("ide:close-tab-requested"),
	ideDiffRequested: makeEvent<IdeDiffRequested>("ide:diff-requested"),
	ideSaveRequested: makeEvent<IdeSaveRequested>("ide:save-requested"),
	ideStatusChanged: makeEvent<IdeStatusChanged>("ide:status-changed"),
	layoutChanged: makeEvent<LayoutChanged>("layout:changed"),
	lspInstallProgress: makeEvent<LspInstallProgress>("lsp:install-progress"),
	lspSessionStatusChanged: makeEvent<LspSessionStatusChanged>("lsp:session-status-changed"),
	projectActivated: makeEvent<ProjectActivated>("project:activated"),
	projectClosed: makeEvent<ProjectClosed>("project:closed"),
	projectFocusKindChanged: makeEvent<ProjectFocusKindChanged>("project:focus-kind-changed"),
	projectListChanged: makeEvent<ProjectListChanged>("project:list-changed"),
	projectOpened: makeEvent<ProjectOpened>("project:opened"),
	remoteStateChanged: makeEvent<RemoteStateChanged>("remote:state-changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings:changed"),
	syncStateChanged: makeEvent<SyncStateChanged>("sync:state-changed"),
	terminalCwdChanged: makeEvent<TerminalCwdChanged>("terminal:cwd-changed"),
	terminalExited: makeEvent<TerminalExited>("terminal:exited"),
	themeChanged: makeEvent<ThemeChanged>("theme:changed"),
};

/* Types */
export type AgentActivity = "idle" | "working" | "awaitingInput" | "unknown";

export type AgentExternalOpen = {
	request: ExternalOpenRequest,
};

export type AgentHooksStatus = {
	agentName: string,
	scope: HookInstallScope,
	installed: boolean,
};

export type AgentStateChanged = {
	projectId: ProjectId,
	agents: DetectedAgent[],
};

export type AheadBehind = {
	ahead: number,
	behind: number,
};

export type AiCommitMessageRequest = {
	requestId: string,
	provider?: AiProviderId | null,
	model?: string | null,
	diffText: string,
	recentCommits: string,
};

export type AiCommitMessageResponse = {
	requestId: string,
	text: string | null,
};

export type AiInlineCompleteRequest = {
	requestId: string,
	provider: AiProviderId,
	model: string,
	prefix: string,
	suffix: string,
	language: string,
	filePath: string,
};

export type AiInlineCompleteResponse = {
	requestId: string,
	text: string | null,
};

export type AiInlineEditRequest = {
	requestId: string,
	provider?: AiProviderId | null,
	model?: string | null,
	selection: string,
	instruction: string,
	language: string,
	filePath: string,
	prefix: string,
	suffix: string,
};

export type AiInlineEditResponse = {
	requestId: string,
	text: string | null,
};

export type AiModelInfo = {
	modelId: string,
	displayName: string | null,
};

export type AiProviderId = "ollamaCloud" | "codex" | "omlx";

export type AiTokenStatus = {
	ollamaCloud: boolean,
	codex: boolean,
	omlx: boolean,
};

export type AppDataPathKind = "plugins" | "themes" | "locales" | "snippets";

export type AppError = { code: "Io"; message: string } | { code: "NotFound"; message: string } | { code: "InvalidArgument"; message: string } | { code: "Forbidden"; message: string } | { code: "Internal"; message: string };

/**
 *  Which app-owned config file an `AppFile` tab (or `app_file_read`/`app_file_write`) addresses.
 *  `AppPaths`-derived on the Rust side only — neither variant carries a path, so the frontend and
 *  the persisted layout JSON never see an absolute filesystem path for these tabs (contract §3.3).
 */
export type AppFileTarget = { kind: "settings" } | { kind: "prompt"; id: PromptTemplateId };

export type AppInfo = {
	name: string,
	version: string,
	platform: string,
	arch: string,
};

export type AppReady = {
	version: string,
};

/**
 *  One auxiliary editor window's own pane tree, keyed by `slot` — a project-scoped semantic id
 *  (allocated by `service::next_window_slot`) distinct from the OS-level Tauri window label
 *  (`editor-<n>`, allocated globally by `domain::window::service::next_auxiliary_label`). A window
 *  close returns its tabs to the main tree's tail and drops this entry
 *  (`service::return_auxiliary_window_tabs`) — TAIDE's 0-loss philosophy, unlike VS Code discarding
 *  an auxiliary window's content on close.
 */
export type AuxWindowLayout = {
	slot: number,
	root: PaneNode,
	focusedPane: PaneId,
};

/**
 *  Result of `commands::window_open_auxiliary`. `label` is the Rust-assigned Tauri window label
 *  (`editor-<n>`) the frontend needs to address this specific OS window (e.g. to correlate it
 *  against `getAllWebviewWindows()`); `project_id`/`window_slot` echo the request back so the
 *  caller doesn't have to thread its own copies through the async round-trip.
 */
export type AuxiliaryWindowInfo = {
	label: string,
	projectId: ProjectId,
	windowSlot: number,
};

export type BlameLine = {
	line: number,
	commitId: string,
	author: string,
	timeUnix: number | null,
	summary: string,
	isUncommitted: boolean,
};

export type CapabilityKind = "git" | "lsp" | "terminal" | "agentWatch";

export type CliInstallStatus = {
	installed: boolean,
	resolvedPath?: string | null,
	/**
	 *  True when the symlink exists but its target can no longer be resolved
	 *  (e.g. the app bundle moved or was removed) — a reinstall is needed.
	 */
	dangling?: boolean,
	targetPath: string,
	editorEnvHint: string,
};

export type ClosedTab = {
	tab: Tab,
	paneId: PaneId,
	index: number,
};

export type CommitFile = {
	path: string,
	/**
	 *  Absolute counterpart to `path` — see `StatusRow::abs_path`'s doc comment for why a
	 *  repo-relative path alone isn't safe for the file domain to open/save against.
	 */
	absPath: string,
	origPath?: string | null,
	/**  Absolute counterpart to `orig_path` — present exactly when `orig_path` is. */
	origAbsPath?: string | null,
	kind: GitChangeKind,
};

export type CommitOptions = {
	amend?: boolean,
	stageAll?: boolean,
};

/**
 *  The three sides of an unresolved merge conflict, keyed by index stage
 *  (1 = ancestor/base, 2 = ours, 3 = theirs), plus the file's current
 *  on-disk content. A side is `None` when that stage has no entry — e.g.
 *  the ancestor is absent for an add/add conflict, or "ours"/"theirs" is
 *  absent for a delete/modify conflict.
 */
export type ConflictSides = {
	base?: string | null,
	ours?: string | null,
	theirs?: string | null,
	workdir: string,
};

export type DetectedAgent = {
	sessionId: string,
	name: string,
	pid: number,
	activity: AgentActivity,
};

export type DiffMode = "workdirVsIndex" | "indexVsHead";

export type DiffSides = {
	original: string,
	modified: string,
	languageId: string,
};

export type DropEdge = "left" | "right" | "top" | "bottom" | "center";

/**
 *  `Settings.editorCursorBlinking` / `SettingsPatch.editorCursorBlinking`'s value set — mirrors
 *  `EditorCursorBlinkingStyle` (`src/features/editor/code-editor.tsx`), Monaco's `cursorBlinking`
 *  option. See [`EditorRenderWhitespace`]'s doc comment for why this is a narrowed enum rather than
 *  `String`.
 */
export type EditorCursorBlinking = "blink" | "smooth" | "phase" | "expand" | "solid";

/**
 *  `Settings.editorCursorStyle` / `SettingsPatch.editorCursorStyle`'s value set — mirrors
 *  `EditorCursorStyle` (`src/features/editor/code-editor.tsx`), Monaco's `cursorStyle` option. See
 *  [`EditorRenderWhitespace`]'s doc comment for why this is a narrowed enum rather than `String`.
 */
export type EditorCursorStyle = "line" | "block" | "underline";

/**
 *  `Settings.editorRenderWhitespace` / `SettingsPatch.editorRenderWhitespace`'s value set — mirrors
 *  `EditorRenderWhitespace` (`src/features/editor/code-editor.tsx`), the Monaco `renderWhitespace`
 *  option's own literal union. Was a bare `Option<String>` (audit
 *  `docs/quality-assurance/2026-08-18-architecture-audit.md` C6/T1-B), which forced 9 frontend `as`
 *  casts and let a hand-edited `settings.json`/synced gist carry an arbitrary string. Narrowing to a
 *  real enum makes specta emit the same `"none" | "boundary" | "selection" | "all"` union the
 *  frontend already hand-declared, so those casts collapse to a plain type. A legacy/out-of-range
 *  value is normalized back to the default *before* typed parse — see
 *  [`crate::domain::settings::service::sanitize_legacy_settings_values`].
 */
export type EditorRenderWhitespace = "none" | "boundary" | "selection" | "all";

export type ExternalOpenRequest = {
	path: string,
	waitMarker?: string | null,
};

export type FileSizeTier = "normal" | "large" | "readOnly" | "refused";

export type FocusKind = "file" | "terminal" | "settings" | "diff" | "claudeDiff" | "welcome" | "untitled" | "searchEditor" | "appFile";

export type FontFamily = {
	name: string,
	monospaced: boolean,
};

export type FsChange = {
	kind: FsChangeKind,
	paths: string[],
	fromApp: boolean,
};

export type FsChangeKind = "created" | "modified" | "removed" | "renamed";

export type FsChanged = {
	projectId: ProjectId,
	change: FsChange,
};

export type GitBranch = {
	name: string,
	isHead: boolean,
	isRemote: boolean,
	upstream: string | null,
};

export type GitChangeKind = "modified" | "added" | "deleted" | "renamed" | "untracked" | "typeChange" | "conflicted";

export type GitRefsChanged = {
	projectId: ProjectId,
};

export type GitRemote = {
	name: string,
	url: string,
};

export type GitStashEntry = {
	index: number,
	message: string,
};

export type GitStatus = {
	rows: StatusRow[],
	branch: string | null,
	ahead: number,
	behind: number,
	hasRemote: boolean,
};

export type GitStatusChanged = {
	projectId: ProjectId,
};

export type GutterHunk = {
	kind: HunkKind,
	start: number,
	end: number,
};

export type HookInstallScope = "project" | "user";

/**
 *  Emitted once when the OS requests the window to close, asking the
 *  frontend to flush every dirty editor model to the hot-exit mirror before
 *  the app actually exits. `timeout_ms` mirrors `HOT_EXIT_FLUSH_TIMEOUT_MS`
 *  so the frontend never needs its own copy of that constant.
 */
export type HotExitFlushRequested = {
	timeoutMs: number | null,
};

export type HunkKind = "added" | "modified" | "deleted";

export type IdeCloseTabRequested = {
	tabName: string,
	requestId: string | null,
};

export type IdeDiagnostic = {
	path: string,
	severity: IdeDiagnosticSeverity,
	startLine: number,
	startCharacter: number,
	endLine: number,
	endCharacter: number,
	message: string,
	source?: string | null,
};

export type IdeDiagnosticSeverity = "error" | "warning" | "info" | "hint";

export type IdeDiffOutcome = "saved" | "rejected" | "tabClosed";

export type IdeDiffRequested = {
	requestId: string,
	projectId: ProjectId,
	oldPath: string,
	newPath: string,
	newContents: string,
	tabName: string,
};

export type IdeSaveRequested = {
	requestId: string,
	projectId: ProjectId,
	path: string,
};

export type IdeSelectionInput = {
	projectId: ProjectId,
	path: string,
	text: string,
	startLine: number,
	startCharacter: number,
	endLine: number,
	endCharacter: number,
	isEmpty: boolean,
};

export type IdeStatus = {
	running: boolean,
	port: number,
	connected: boolean,
	clientCount: number,
};

export type IdeStatusChanged = {
	status: IdeStatus,
};

export type LayoutChanged = {
	projectId: ProjectId,
	revision: number,
};

export type LoadedPlugin = {
	manifest: PluginManifest,
	root: string,
	enabled: boolean,
	error?: PluginErrorCode | null,
};

export type LocaleSummary = {
	id: string,
	name: string,
	builtin: boolean,
};

export type LogEntry = {
	id: string,
	parents: string[],
	summary: string,
	author: string,
	timeUnix: number | null,
	refs: string[],
};

/**
 *  Structural mirror of an arbitrary JSON value, used only as the `#[specta(type = ...)]`
 *  export target for `LspServerDetection::initialization_options`. Specta's built-in
 *  `serde_json::Value` mapping cannot be exported to TypeScript because its number
 *  representation carries `i64`/`u64`, which Specta forbids (precision-loss guard). This type
 *  is never constructed at runtime — the real field keeps `serde_json::Value` so the JSON
 *  payload forwarded from the LSP manifest is unaffected.
 */
export type LspInitializationOptionsValue = boolean | number | null | string | (LspInitializationOptionsValue | null)[] | { [key in string]: LspInitializationOptionsValue | null };

export type LspInstallPhase = "downloading" | "verifying" | "extracting" | "done" | "failed";

export type LspInstallProgress = {
	serverId: LspServerId,
	phase: LspInstallPhase,
	receivedBytes: number | null,
	totalBytes: number | null,
	message?: string | null,
};

export type LspInstallStrategy = "download" | "toolchain" | "sdk-detect";

export type LspServerDetection = {
	id: LspServerId,
	name: string,
	languageIds: string[],
	resolvedPath?: string | null,
	available: boolean,
	installHint?: string | null,
	installStrategy: LspInstallStrategy,
	installedVersion?: string | null,
	toolchainAvailable?: boolean | null,
	sdkAvailable?: boolean | null,
	toolchainTool?: string | null,
	downloadAvailable?: boolean | null,
	initializationOptions?: LspInitializationOptionsValue | null,
};

export type LspServerId = string;

export type LspSessionInfo = {
	sessionId: string,
	projectId: ProjectId,
	serverId: LspServerId,
	root: string,
	status: LspSessionStatus,
	lastError?: string | null,
};

export type LspSessionStatus = "starting" | "running" | "crashed" | "stopped";

export type LspSessionStatusChanged = {
	sessionId: string,
	status: LspSessionStatus,
	lastError: string | null,
};

/**
 *  `lsp_spawn`'s business-identity args, grouped into one struct (mirroring
 *  `terminal::types::PtySpawnOptions`) purely to stay under `clippy::too_many_arguments` once
 *  `owner` (window-scoped session reuse — see the `channels` field doc on `lsp::commands::SessionEntry`)
 *  joined `project_id`/`server_id`/`root` as a fourth plain argument. `on_message` (the `Channel`)
 *  stays a separate top-level command parameter, matching `pty_spawn`'s `opts`/`on_data` split.
 */
export type LspSpawnRequest = {
	projectId: ProjectId,
	serverId: LspServerId,
	root: string,
	owner: string,
};

/**
 *  A restorable hot-exit mirror, resolved against the file's *current* disk
 *  state at list time. `conflict` is `true` when the disk was modified after
 *  the mirror's `disk_modified_ms` baseline was captured, meaning applying
 *  the mirror as-is would silently discard an external change.
 */
export type MirrorEntry = {
	path: string,
	content: string,
	savedAtMs: number | null,
	diskModifiedMs: number | null,
	conflict: boolean,
};

export type OpenedFile = {
	path: string,
	content: string,
	languageId: string,
	byteSize: number,
	lineCount: number,
	tier: FileSizeTier,
	readOnly: boolean,
	modifiedMs: number | null,
};

export type PaneId = string;

export type PaneNode = { node: "split"; id: PaneId; dir: SplitDir; children: PaneNode[]; sizes: (number | null)[] } | { node: "leaf"; id: PaneId; tabs: Tab[]; active: TabId | null };

export type PluginContributions = {
	languages?: PluginLanguageContribution[],
	lsp?: PluginLspContribution[],
	themes?: PluginThemeContribution[],
};

export type PluginErrorCode = "parse-failed" | "id-mismatch" | "version-mismatch" | "path-escape" | "grammar-missing" | "grammar-invalid" | "grammar-conflict";

export type PluginLanguageContribution = {
	id: string,
	extensions: string[],
	aliases?: string[],
	grammar?: string | null,
	embeddedLanguages?: string[] | null,
};

export type PluginLspContribution = {
	languageId: string,
	id: string,
	cmd: string,
	args?: string[],
	detect?: string[],
	shareable?: boolean,
	installInstructions?: string | null,
};

export type PluginManifest = {
	manifestVersion: number,
	id: string,
	name: string,
	version: string,
	contributes?: PluginContributions,
};

export type PluginThemeContribution = {
	id: string,
	path: string,
};

export type Project = {
	id: ProjectId,
	root: string,
	name: string,
	capabilities?: CapabilityKind[],
	rootMissing?: boolean,
};

export type ProjectActivated = {
	projectId: ProjectId | null,
};

export type ProjectAgents = {
	projectId: ProjectId,
	agents: DetectedAgent[],
};

export type ProjectClosed = {
	projectId: ProjectId,
};

export type ProjectFocusKindChanged = {
	projectId: ProjectId,
	kind: FocusKind,
};

export type ProjectId = string;

export type ProjectLayout = {
	version: number,
	root: PaneNode,
	focusedPane: PaneId,
	revision?: number,
	closedTabs?: ClosedTab[],
	auxiliaryWindows?: AuxWindowLayout[],
	shellView?: ShellViewState,
};

export type ProjectListChanged = {
	projects: ProjectRef[],
};

export type ProjectOpenResult = {
	project: Project,
	alreadyOpen: boolean,
};

export type ProjectOpened = {
	project: Project,
};

export type ProjectRef = {
	id: ProjectId,
	root: string,
	name: string,
};

/**
 *  Closed set of prompt-template overrides editable through an `AppFile` tab — deliberately a real
 *  enum (not a raw `String` id) so an invalid id can never reach `app::service::app_file_path` in
 *  the first place; there is no runtime whitelist check to forget. Variant names are the
 *  kebab-case-serialized wire form (`#[serde(rename_all = "kebab-case")]` below), matching
 *  `ai::prompt`'s existing `*_PROMPT_ID` constants exactly — [`PromptTemplateId::as_str`] ties the
 *  two together so the file name on disk and the id embedded in a tab never drift independently.
 */
export type PromptTemplateId = "auto-tab-default" | "inline-edit-default" | "commit-message-default";

export type PtySpawnOptions = {
	projectId: ProjectId,
	cwd: string,
	shell?: string | null,
	cols: number,
	rows: number,
};

export type RemoteLinkInfo = {
	url: string,
};

export type RemoteStateChanged = {
	status: RemoteStatus,
};

export type RemoteStatus = {
	running: boolean,
	port: number,
	clientCount: number,
	passwordConfigured: boolean,
};

export type ResolvedLocale = ResolvedLocale_Serialize | ResolvedLocale_Deserialize;

export type ResolvedLocale_Deserialize = {
	id: string,
	name: string,
	messages: { [key in string]: string },
	warnings?: string[],
};

export type ResolvedLocale_Serialize = {
	id: string,
	name: string,
	messages: { [key in string]: string },
	warnings?: string[],
};

export type ResolvedTheme = ResolvedTheme_Serialize | ResolvedTheme_Deserialize;

export type ResolvedTheme_Deserialize = {
	id: string,
	name: string,
	type: ThemeType,
	colors: { [key in string]: string },
	syntax: { [key in string]: SyntaxStyle },
	terminal: { [key in string]: string },
	tokenColors?: TokenColorRule_Deserialize[] | null,
	syntaxOverrides?: string[],
	warnings?: string[],
	author?: string | null,
	license?: string | null,
	source?: string | null,
};

export type ResolvedTheme_Serialize = {
	id: string,
	name: string,
	type: ThemeType,
	colors: { [key in string]: string },
	syntax: { [key in string]: SyntaxStyle },
	terminal: { [key in string]: string },
	tokenColors?: TokenColorRule_Serialize[] | null,
	syntaxOverrides: string[],
	warnings: string[],
	author: string | null,
	license: string | null,
	source: string | null,
};

export type RevertOutcome = {
	conflicted: boolean,
	/**
	 *  Paths left with unresolved conflict markers, so the caller can route the user straight to
	 *  them (e.g. open the first one) instead of leaving conflict resolution to be discovered via
	 *  the next status refresh. Always empty when `conflicted` is `false`. Repo-relative (`git2`
	 *  index paths) — see `conflicted_abs_paths` for the file domain's absolute counterpart.
	 */
	conflictedPaths: string[],
	/**
	 *  Absolute counterpart to `conflicted_paths` (workdir root joined onto each entry, same
	 *  order/length). The file domain's entry points only accept absolute paths — see
	 *  `StatusRow::abs_path`'s doc comment for why a repo-relative path must not reach `file_open`.
	 */
	conflictedAbsPaths: string[],
};

export type SearchMatch = {
	path: string,
	line: number,
	/**
	 *  1-based, in UTF-16 code units — Monaco `Position.column`'s own convention, so the frontend
	 *  can hand this straight to `reveal-registry.ts` without converting. Computed from the UTF-8
	 *  byte offset `search::service::search_file` matches at via
	 *  `search::service::byte_offset_to_utf16_units`.
	 */
	column: number,
	preview: string,
	/**
	 *  0-based UTF-16 code unit offsets into `preview` — `preview` is consumed as a JS string via
	 *  `preview.slice(matchStart, matchEnd)`, which indexes by UTF-16 code unit, not UTF-8 byte.
	 */
	matchStart: number,
	matchEnd: number,
	/**
	 *  Up to `SearchQuery::context_lines` lines immediately before the match
	 *  line, in file order. Empty when `context_lines` is `0`.
	 */
	before: string[],
	/**
	 *  Up to `SearchQuery::context_lines` lines immediately after the match
	 *  line, in file order. Empty when `context_lines` is `0`.
	 */
	after: string[],
};

export type SearchQuery = {
	text: string,
	caseSensitive?: boolean,
	wholeWord?: boolean,
	regex?: boolean,
	includeGlob?: string | null,
	excludeGlob?: string | null,
	contextLines?: number,
	respectGitignore?: boolean,
};

export type SearchReplaceResult = {
	changedFiles: number,
	replacedMatches: number,
};

export type Settings = {
	version: number,
	themeId?: string,
	editorFontSize?: number,
	terminalFontSize?: number,
	shellOverride?: string | null,
	followSystemTheme?: boolean,
	language?: string,
	toastPosition?: string,
	resizerThickness?: number,
	editorFontFamily?: string | null,
	terminalFontFamily?: string | null,
	uiFontFamily?: string | null,
	formatOnSave?: boolean,
	autoSaveDelayMs?: number,
	keymapOverrides?: string | null,
	editorMinimap?: boolean,
	showSystemUsage?: boolean,
	agentStatusBadgeEnabled?: boolean,
	agentHooksEnabled?: boolean,
	ideIntegrationEnabled?: boolean,
	ideAutoOpenDiff?: boolean,
	editorWordWrap?: boolean,
	editorLineNumbers?: boolean,
	editorTabSize?: number,
	editorInsertSpaces?: boolean,
	editorDetectIndentation?: boolean,
	editorRenderWhitespace?: EditorRenderWhitespace,
	editorBracketPairColorization?: boolean,
	editorFontLigatures?: boolean,
	editorCursorStyle?: EditorCursorStyle,
	editorCursorBlinking?: EditorCursorBlinking,
	editorScrollBeyondLastLine?: boolean,
	editorStickyScrollEnabled?: boolean,
	terminalScrollback?: number,
	terminalCursorStyle?: TerminalCursorStyle,
	terminalCursorBlink?: boolean,
	enablePreviewTabs?: boolean,
	aiAutoTabEnabled?: boolean,
	/**
	 *  Renamed from `ai_auto_tab_provider` — this field now backs every AI feature's default
	 *  provider (auto-tab, Inline Edit, AI commit messages), not just auto-tab, so the name was
	 *  generalized. A pre-rename `settings.json`/synced gist payload (`aiAutoTabProvider`) is
	 *  migrated to this field name by
	 *  [`crate::domain::settings::service::migrate_legacy_ai_provider_keys`] before
	 *  deserialization — deliberately *not* a `#[serde(alias = ...)]` on this field, since with
	 *  the `specta` version this project pins, an alias makes `Settings`' Serialize and
	 *  Deserialize shapes diverge, splitting every TS consumer of `Settings` (including ones
	 *  unrelated to this field) into `_Serialize`/`_Deserialize`/union type variants. See
	 *  `docs/acknowledge/2026-08-16-wave-g-ai-contract.md` §2-2/§3.1.
	 * 
	 *  `Option<AiProviderId>` (not a locally-declared enum) reuses the same type the `ai_*`
	 *  commands already validate `provider` arguments against (`domain::ai::types::AiProviderId`),
	 *  instead of `Option<String>` plus the hand-maintained `AI_PROVIDERS` allow-list `sanitize()`
	 *  used to check it against — see [`EditorRenderWhitespace`]'s doc comment for why an
	 *  out-of-range value is normalized before typed parse rather than accepted here as `None`.
	 */
	aiProvider?: AiProviderId | null,
	/**  Renamed from `ai_auto_tab_model` — see [`Settings::ai_provider`]'s doc comment. */
	aiModel?: string | null,
	aiOmlxBaseUrl?: string | null,
	syncGistId?: string | null,
	syncLastSyncedAt?: string | null,
	remoteAccessEnabled?: boolean,
	remotePasswordOnlyLogin?: boolean,
	remoteAllowedHosts?: string[],
	organizeImportsOnSave?: boolean,
	fixAllOnSave?: boolean,
	editorCodeLensEnabled?: boolean,
	editorSemanticHighlighting?: boolean,
	editorFormatOnType?: boolean,
	editorFormatOnPaste?: boolean,
	emmetEnabled?: boolean,
	/**
	 *  Most-recent-first search terms, newest at index `0`. The cap
	 *  (currently 20) and dedup/prepend logic are the frontend's
	 *  responsibility (`entities/search`) — this field is a plain passthrough,
	 *  same as `remote_allowed_hosts`' list shape but without server-side
	 *  validation, since search history carries no security weight. See
	 *  `docs/acknowledge/2026-08-15-wave-d-search-nav-contract.md` §3.5.
	 */
	recentSearches?: string[],
	/**
	 *  When `true`, entering Zen mode also fullscreens the main window
	 *  (`window::commands::window_set_fullscreen`). Defaults to `false` — Zen mode's chrome hiding
	 *  is opt-out (`zen_hide_status_bar`), but fullscreen is opt-in, since it also affects the OS
	 *  window itself, not just TAIDE's own chrome. See
	 *  `docs/acknowledge/2026-08-16-wave-i-shell-workspace-contract.md` §3.2.
	 */
	zenFullscreen?: boolean,
	/**
	 *  Whether Zen mode hides the status bar in addition to the sidebar/tab bar it always hides.
	 *  Defaults to `true`.
	 */
	zenHideStatusBar?: boolean,
};

/**
 *  Emitted after every settings write reaches the shared reapply path
 *  (`settings::commands::apply_and_broadcast`) — a `settings_update` patch, a `sync_download`, or an
 *  `app_file_write` on the `Settings` target. Carries the full sanitized `Settings` so a listener
 *  can update immediately without a round-trip, though the frontend's own convention is to
 *  invalidate its cached `SETTINGS.CURRENT` query and let TanStack Query refetch
 *  (`docs/acknowledge/2026-08-16-wave-i-shell-workspace-contract.md` §3.3).
 */
export type SettingsChanged = {
	settings: Settings,
};

export type SettingsPatch = {
	themeId: string | null,
	editorFontSize: number | null,
	terminalFontSize: number | null,
	shellOverride: string | null,
	followSystemTheme: boolean | null,
	language: string | null,
	toastPosition: string | null,
	resizerThickness: number | null,
	editorFontFamily: string | null,
	terminalFontFamily: string | null,
	uiFontFamily: string | null,
	formatOnSave: boolean | null,
	autoSaveDelayMs: number | null,
	keymapOverrides: string | null,
	editorMinimap: boolean | null,
	showSystemUsage: boolean | null,
	agentStatusBadgeEnabled: boolean | null,
	agentHooksEnabled: boolean | null,
	ideIntegrationEnabled: boolean | null,
	ideAutoOpenDiff: boolean | null,
	editorWordWrap: boolean | null,
	editorLineNumbers: boolean | null,
	editorTabSize: number | null,
	editorInsertSpaces: boolean | null,
	editorDetectIndentation: boolean | null,
	editorRenderWhitespace: EditorRenderWhitespace | null,
	editorBracketPairColorization: boolean | null,
	editorFontLigatures: boolean | null,
	editorCursorStyle: EditorCursorStyle | null,
	editorCursorBlinking: EditorCursorBlinking | null,
	editorScrollBeyondLastLine: boolean | null,
	editorStickyScrollEnabled: boolean | null,
	terminalScrollback: number | null,
	terminalCursorStyle: TerminalCursorStyle | null,
	terminalCursorBlink: boolean | null,
	enablePreviewTabs: boolean | null,
	aiAutoTabEnabled: boolean | null,
	aiProvider: AiProviderId | null,
	aiModel: string | null,
	aiOmlxBaseUrl: string | null,
	remoteAccessEnabled: boolean | null,
	remotePasswordOnlyLogin: boolean | null,
	remoteAllowedHosts: string[] | null,
	organizeImportsOnSave: boolean | null,
	fixAllOnSave: boolean | null,
	editorCodeLensEnabled: boolean | null,
	editorSemanticHighlighting: boolean | null,
	editorFormatOnType: boolean | null,
	editorFormatOnPaste: boolean | null,
	emmetEnabled: boolean | null,
	recentSearches: string[] | null,
	zenFullscreen: boolean | null,
	zenHideStatusBar: boolean | null,
};

export type ShellProfile = {
	id: string,
	name: string,
	path: string,
	args?: string[],
};

/**
 *  Partial update for [`ShellViewState`] — `None` fields are left at their current value, same
 *  merge convention as `settings::service::SettingsPatch`/`apply_patch`.
 */
export type ShellViewPatch = {
	zen: boolean | null,
	sidebarCollapsed: boolean | null,
};

/**
 *  Per-project display-chrome state for the **main** window only — auxiliary windows are
 *  sidebar/status-bar-less editor chrome by design (contract §3.2), so this isn't per-window.
 */
export type ShellViewState = {
	zen?: boolean,
	sidebarCollapsed?: boolean,
};

/**
 *  One named snippet entry, matching VS Code's `<languageId>.json` /
 *  `*.code-snippets` schema. `scope` only has meaning inside a
 *  `.code-snippets` file (a comma-separated `languageId` list); it is kept as
 *  a plain optional field here and interpreted by the frontend completion
 *  provider (`docs/acknowledge/2026-08-15-wave-f-editor-presentation-contract.md`
 *  §3.3). `isFileTemplate`/`include`/`exclude` from the upstream schema are
 *  intentionally not modeled — unknown JSON fields are dropped silently by
 *  serde's default (non-`deny_unknown_fields`) behavior, matching the
 *  contract's "1차 무시" decision.
 */
export type SnippetEntry = SnippetEntry_Serialize | SnippetEntry_Deserialize;

/**
 *  One named snippet entry, matching VS Code's `<languageId>.json` /
 *  `*.code-snippets` schema. `scope` only has meaning inside a
 *  `.code-snippets` file (a comma-separated `languageId` list); it is kept as
 *  a plain optional field here and interpreted by the frontend completion
 *  provider (`docs/acknowledge/2026-08-15-wave-f-editor-presentation-contract.md`
 *  §3.3). `isFileTemplate`/`include`/`exclude` from the upstream schema are
 *  intentionally not modeled — unknown JSON fields are dropped silently by
 *  serde's default (non-`deny_unknown_fields`) behavior, matching the
 *  contract's "1차 무시" decision.
 */
export type SnippetEntry_Deserialize = {
	prefix: SnippetStringOrList,
	body: SnippetStringOrList,
	description?: SnippetStringOrList | null,
	scope?: string | null,
};

/**
 *  One named snippet entry, matching VS Code's `<languageId>.json` /
 *  `*.code-snippets` schema. `scope` only has meaning inside a
 *  `.code-snippets` file (a comma-separated `languageId` list); it is kept as
 *  a plain optional field here and interpreted by the frontend completion
 *  provider (`docs/acknowledge/2026-08-15-wave-f-editor-presentation-contract.md`
 *  §3.3). `isFileTemplate`/`include`/`exclude` from the upstream schema are
 *  intentionally not modeled — unknown JSON fields are dropped silently by
 *  serde's default (non-`deny_unknown_fields`) behavior, matching the
 *  contract's "1차 무시" decision.
 */
export type SnippetEntry_Serialize = {
	prefix: SnippetStringOrList,
	body: SnippetStringOrList,
	description?: SnippetStringOrList | null,
	scope?: string | null,
};

/**
 *  One snippet file plus its parsed contents, as returned by `snippet_list`.
 *  The frontend's completion provider derives the file's `languageId` from
 *  `file_name` itself (`<languageId>.json` vs. global `*.code-snippets`) —
 *  see the contract §3.3 — so no separate language field is carried here.
 */
export type SnippetFile = SnippetFile_Serialize | SnippetFile_Deserialize;

/**
 *  One snippet file plus its parsed contents, as returned by `snippet_list`.
 *  The frontend's completion provider derives the file's `languageId` from
 *  `file_name` itself (`<languageId>.json` vs. global `*.code-snippets`) —
 *  see the contract §3.3 — so no separate language field is carried here.
 */
export type SnippetFile_Deserialize = {
	fileName: string,
	snippets: { [key in string]: SnippetEntry_Deserialize },
};

/**
 *  One snippet file plus its parsed contents, as returned by `snippet_list`.
 *  The frontend's completion provider derives the file's `languageId` from
 *  `file_name` itself (`<languageId>.json` vs. global `*.code-snippets`) —
 *  see the contract §3.3 — so no separate language field is carried here.
 */
export type SnippetFile_Serialize = {
	fileName: string,
	snippets: { [key in string]: SnippetEntry_Serialize },
};

/**
 *  A VS Code snippet field that accepts either a single line or an array of
 *  lines (`prefix`, `body`, `description` in the upstream schema all share
 *  this shape). `#[serde(untagged)]` picks whichever variant matches the JSON
 *  value on the wire, so callers don't need a discriminant field.
 */
export type SnippetStringOrList = string | string[];

export type SplitDir = "horizontal" | "vertical";

/**
 *  Unified diff text of staged changes (HEAD vs index), for AI commit message generation
 *  (`ai_commit_message`) — see [`crate::domain::git::service::diff_staged_text`] for how
 *  `truncated`/`skipped_files` get populated. `used_fallback` is `true` when the index had no
 *  staged deltas against HEAD and `diff_text` was built from the working tree instead (Wave H
 *  unstaged fallback, `docs/acknowledge/2026-08-16-wave-h-keymap-contract.md` §3.4).
 */
export type StagedDiffText = {
	diffText: string,
	truncated: boolean,
	skippedFiles: string[],
	usedFallback: boolean,
};

export type StatusRow = {
	path: string,
	/**
	 *  Absolute filesystem path for `path`, computed by joining the repository's workdir root.
	 *  `path` alone is repo-relative (as `git2`'s status API returns it), but the file domain's
	 *  entry points (`file_open`/`file_save`/`root_guard::resolve_owning_project`) only accept
	 *  absolute paths — a consumer that mistakenly treated a repo-relative `path` as one resolved
	 *  against the *current* project's root, instead of joining it against *this row's* repo root,
	 *  opened or saved the wrong file whenever those two roots differ (multi-root workspace, a
	 *  worktree, or the git panel showing a background project). See
	 *  `docs/acknowledge/2026-08-18-audit-t0-fix-contract.md` §1 결정 8.
	 */
	absPath: string,
	origPath?: string | null,
	/**  Absolute counterpart to `orig_path` — present exactly when `orig_path` is. */
	origAbsPath?: string | null,
	staged?: GitChangeKind | null,
	unstaged?: GitChangeKind | null,
	isConflicted: boolean,
};

export type SyncDownloadResult = { kind: "applied"; status: SyncStatus } | { kind: "conflict"; remoteUpdatedAt: string };

export type SyncStateChanged = {
	status: SyncStatus,
};

export type SyncStatus = {
	connected: boolean,
	hasGist: boolean,
	lastSyncedAt: string | null,
	remoteNewer: boolean | null,
};

export type SyntaxStyle = {
	fg: string,
	bold?: boolean,
	italic?: boolean,
};

export type SystemUsage = {
	cpuPercent: number | null,
	memoryBytes: number | null,
};

export type SystemUsageProcess = {
	pid: number,
	kind: SystemUsageProcessKind,
	label: string,
	/**
	 *  `null` until this pid has survived one prior breakdown refresh — sysinfo reports
	 *  `cpu_usage() == 0.0` for a pid it has never refreshed before, which is indistinguishable
	 *  from a genuinely idle process (ipc-contract.md §기능 확장 2차 계약 확정 추가).
	 */
	cpuPercent: number | null,
	memoryBytes: number | null,
};

export type SystemUsageProcessKind = "app" | "terminal" | "lsp" | "agent" | "other";

export type Tab = {
	id: TabId,
	kind: TabKind,
	title: string,
	pinned?: boolean,
	preview?: boolean,
	dirty?: boolean,
	viewState?: string | null,
};

export type TabId = string;

export type TabKind = { kind: "file"; path: string } | { kind: "terminal"; sessionId: string; cwd?: string | null } | { kind: "settings" } | 
/**
 *  `rev`/`parent_rev`/`before_path` are optional so a tab can additionally represent a
 *  *commit* diff (`git_show_file(rev, path)` vs `git_show_file(parent_rev, before_path ??
 *  path)`), reusing the same `TabKind::Diff` the working-tree/staged diff already uses instead
 *  of a dedicated variant — see
 *  `docs/acknowledge/2026-08-18-hand-qa-fix-contract.md` §2.6. `#[serde(default)]` on all
 *  three keeps a pre-existing `layout.json` (written before this field set existed)
 *  deserializing unchanged, the same backward-compatibility `compare_with` already relies on.
 */
{ kind: "diff"; path: string; staged: boolean; compareWith?: string | null; rev?: string | null; parentRev?: string | null; beforePath?: string | null } | { kind: "claudeDiff"; requestId: string; path: string } | { kind: "welcome" } | { kind: "untitled"; index: number } | 
/**
 *  A persistent, editable search results surface (VS Code calls this a "Search Editor").
 *  Only the query is kept — results are cheap to re-run (`search::commands::search_run`)
 *  and streaming a potentially large `SearchMatch` list through hot-exit/session-restore
 *  JSON would bloat the layout file for no benefit, so the tab restores to the query and
 *  re-searches rather than replaying stale results. See
 *  `docs/acknowledge/2026-08-15-wave-d-search-nav-contract.md` §3.4.
 */
{ kind: "searchEditor"; query: SearchQuery } | 
/**
 *  An app-owned config file (`settings.json` or a prompt template override) opened as a tab —
 *  unlike `File`, its path is never carried in the tab itself: `target` is a closed enum Rust
 *  resolves to an `AppPaths`-derived location (`app::service::app_file_path`), so neither the
 *  layout JSON nor the frontend ever sees an absolute path for it. See
 *  `docs/acknowledge/2026-08-16-wave-i-shell-workspace-contract.md` §3.3.
 */
{ kind: "appFile"; target: AppFileTarget };

/**
 *  Destination for `layout_move_tab_to_window`. `Existing` addresses an auxiliary window already
 *  recorded in `ProjectLayout::auxiliary_windows` by its project-scoped `slot`; `NewAuxiliary`
 *  allocates a fresh slot (`service::next_window_slot`) and asks `domain::window` to open a real OS
 *  window for it before the tab lands there.
 */
export type TabWindowTarget = { kind: "main" } | { kind: "newAuxiliary" } | { kind: "existing"; slot: number };

export type TagCreateOptions = {
	message?: string | null,
	annotated?: boolean,
};

export type TagInfo = {
	name: string,
	target: string,
	message?: string | null,
	annotated: boolean,
};

export type Task = {
	label: string,
	command: string,
	source: TaskSource,
	cwd: string,
};

export type TaskSource = "npm" | "make" | "cargo";

/**
 *  `Settings.terminalCursorStyle` / `SettingsPatch.terminalCursorStyle`'s value set — mirrors
 *  `TerminalCursorStyle` (`src/features/terminal/terminal-view.tsx`), xterm.js's `cursorStyle`
 *  option. See [`EditorRenderWhitespace`]'s doc comment for why this is a narrowed enum rather than
 *  `String`.
 */
export type TerminalCursorStyle = "bar" | "block" | "underline";

export type TerminalCwdChanged = {
	sessionId: string,
	cwd: string,
};

export type TerminalExited = {
	sessionId: string,
	code: number | null,
};

export type TerminalSession = {
	id: string,
	projectId: ProjectId,
	cwd: string,
	shell: string,
	running: boolean,
};

export type Theme = Theme_Serialize | Theme_Deserialize;

export type ThemeChanged = {
	themeId: string,
};

export type ThemeSummary = {
	id: string,
	name: string,
	type: ThemeType,
	builtin: boolean,
};

export type ThemeType = "dark" | "light";

export type Theme_Deserialize = {
	version: number,
	id: string,
	name: string,
	type: ThemeType,
	extends?: string | null,
	palette?: { [key in string]: string },
	colors?: { [key in string]: string },
	syntax?: { [key in string]: SyntaxStyle },
	terminal?: { [key in string]: string },
	tokenColors?: TokenColorRule_Deserialize[] | null,
	author?: string | null,
	license?: string | null,
	source?: string | null,
};

export type Theme_Serialize = {
	version: number,
	id: string,
	name: string,
	type: ThemeType,
	extends: string | null,
	palette: { [key in string]: string },
	colors: { [key in string]: string },
	syntax: { [key in string]: SyntaxStyle },
	terminal: { [key in string]: string },
	tokenColors?: TokenColorRule_Serialize[] | null,
	author: string | null,
	license: string | null,
	source: string | null,
};

export type TokenColorRule = TokenColorRule_Serialize | TokenColorRule_Deserialize;

export type TokenColorRule_Deserialize = {
	scope: string[],
	settings: TokenColorSettings_Deserialize,
};

export type TokenColorRule_Serialize = {
	scope: string[],
	settings: TokenColorSettings_Serialize,
};

export type TokenColorSettings = TokenColorSettings_Serialize | TokenColorSettings_Deserialize;

export type TokenColorSettings_Deserialize = {
	foreground?: string | null,
	background?: string | null,
	fontStyle?: string | null,
};

export type TokenColorSettings_Serialize = {
	foreground?: string | null,
	background?: string | null,
	fontStyle?: string | null,
};

export type TreeEntryKind = "file" | "directory";

export type TreeRow = {
	path: string,
	name: string,
	kind: TreeEntryKind,
	depth: number,
	expanded: boolean,
	hasChildren: boolean,
};

export type TreeRowPage = {
	rows: TreeRow[],
	total: number,
};

export type UntitledMirrorEntry = {
	tabId: TabId,
	content: string,
	savedAtMs: number | null,
};

export type VsixExtensionInfo = {
	name: string,
	displayName: string,
	publisher: string,
	version: string,
};

export type VsixExtractedTheme = {
	label: string,
	uiTheme: string,
	rawJson: string,
	includeChain: VsixThemeIncludeEntry[],
};

export type VsixThemeExtractionResult = {
	extension: VsixExtensionInfo,
	themes: VsixExtractedTheme[],
};

export type VsixThemeIncludeEntry = {
	path: string,
	rawJson: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

