// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appGetInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_get_info")),
	projectList: () => typedError<ProjectRef[], AppError>(__TAURI_INVOKE("project_list")),
	projectGet: (projectId: ProjectId) => typedError<Project, AppError>(__TAURI_INVOKE("project_get", { projectId })),
	projectGetActive: () => typedError<string | null, AppError>(__TAURI_INVOKE("project_get_active")),
	projectOpen: (path: string) => typedError<ProjectOpenResult, AppError>(__TAURI_INVOKE("project_open", { path })),
	projectClose: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("project_close", { projectId })),
	projectActivate: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("project_activate", { projectId })),
	projectReorder: (ids: ProjectId[]) => typedError<null, AppError>(__TAURI_INVOKE("project_reorder", { ids })),
	layoutGet: (projectId: ProjectId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_get", { projectId })),
	layoutOpenTab: (projectId: ProjectId, kind: TabKind, title: string, target: string | null, preview: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_open_tab", { projectId, kind, title, target, preview })),
	layoutCloseTab: (tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_close_tab", { tabId })),
	layoutActivateTab: (tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_activate_tab", { tabId })),
	layoutMoveTab: (tabId: TabId, paneId: PaneId, index: number) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_move_tab", { tabId, paneId, index })),
	layoutSplit: (paneId: PaneId, edge: DropEdge, tabId: TabId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_split", { paneId, edge, tabId })),
	layoutResize: (paneId: PaneId, sizes: (number | null)[]) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_resize", { paneId, sizes })),
	layoutFocusPane: (paneId: PaneId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_focus_pane", { paneId })),
	layoutPinTab: (tabId: TabId, pinned: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_pin_tab", { tabId, pinned })),
	layoutReopenClosed: (projectId: ProjectId) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_reopen_closed", { projectId })),
	layoutSetViewState: (tabId: TabId, viewState: string | null) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_view_state", { tabId, viewState })),
	layoutSetDirty: (tabId: TabId, dirty: boolean) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_dirty", { tabId, dirty })),
	layoutSetTerminalSession: (tabId: TabId, sessionId: string) => typedError<ProjectLayout, AppError>(__TAURI_INVOKE("layout_set_terminal_session", { tabId, sessionId })),
	fileOpen: (path: string) => typedError<OpenedFile, AppError>(__TAURI_INVOKE("file_open", { path })),
	fileSave: (path: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("file_save", { path, content })),
	fileCreate: (path: string, isDir: boolean) => typedError<null, AppError>(__TAURI_INVOKE("file_create", { path, isDir })),
	fileRename: (from: string, to: string) => typedError<null, AppError>(__TAURI_INVOKE("file_rename", { from, to })),
	fileDelete: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("file_delete", { path })),
	fileCopy: (from: string, to: string) => typedError<null, AppError>(__TAURI_INVOKE("file_copy", { from, to })),
	fileMirrorDirty: (projectId: ProjectId, path: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("file_mirror_dirty", { projectId, path, content })),
	treeRows: (projectId: ProjectId, offset: number, limit: number) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_rows", { projectId, offset, limit })),
	treeToggle: (projectId: ProjectId, path: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_toggle", { projectId, path })),
	treeReveal: (projectId: ProjectId, path: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_reveal", { projectId, path })),
	treeRefresh: (projectId: ProjectId, dir: string) => typedError<TreeRowPage, AppError>(__TAURI_INVOKE("tree_refresh", { projectId, dir })),
	searchRun: (projectId: ProjectId, query: SearchQuery, onMatch: Channel<SearchMatch>) => typedError<number, AppError>(__TAURI_INVOKE("search_run", { projectId, query, onMatch })),
	searchCancel: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("search_cancel", { projectId })),
	pluginList: () => typedError<LoadedPlugin[], AppError>(__TAURI_INVOKE("plugin_list")),
	pluginReload: () => typedError<LoadedPlugin[], AppError>(__TAURI_INVOKE("plugin_reload")),
	agentList: (projectId: ProjectId) => typedError<ProjectAgents, AppError>(__TAURI_INVOKE("agent_list", { projectId })),
	agentReleaseMarker: (marker: string) => typedError<null, AppError>(__TAURI_INVOKE("agent_release_marker", { marker })),
	agentCliStatus: () => typedError<CliInstallStatus, AppError>(__TAURI_INVOKE("agent_cli_status")),
	lspSpawn: (projectId: ProjectId, serverId: LspServerId, root: string, onMessage: Channel<string>) => typedError<string, AppError>(__TAURI_INVOKE("lsp_spawn", { projectId, serverId, root, onMessage })),
	lspSend: (sessionId: string, message: string) => typedError<null, AppError>(__TAURI_INVOKE("lsp_send", { sessionId, message })),
	lspStop: (sessionId: string, root: string | null) => typedError<null, AppError>(__TAURI_INVOKE("lsp_stop", { sessionId, root })),
	lspRestart: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("lsp_restart", { sessionId })),
	lspSessions: (projectId: ProjectId) => typedError<LspSessionInfo[], AppError>(__TAURI_INVOKE("lsp_sessions", { projectId })),
	lspDetectServers: () => typedError<LspServerDetection[], AppError>(__TAURI_INVOKE("lsp_detect_servers")),
	lspResolveRoot: (serverId: LspServerId, filePath: string) => typedError<string | null, AppError>(__TAURI_INVOKE("lsp_resolve_root", { serverId, filePath })),
	gitStatus: (projectId: ProjectId) => typedError<GitStatus, AppError>(__TAURI_INVOKE("git_status", { projectId })),
	gitDiffFile: (projectId: ProjectId, path: string, mode: DiffMode) => typedError<DiffSides, AppError>(__TAURI_INVOKE("git_diff_file", { projectId, path, mode })),
	gitShowFile: (projectId: ProjectId, rev: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("git_show_file", { projectId, rev, path })),
	gitLog: (projectId: ProjectId, skip: number, take: number) => typedError<LogEntry[], AppError>(__TAURI_INVOKE("git_log", { projectId, skip, take })),
	gitAheadBehind: (projectId: ProjectId) => typedError<AheadBehind, AppError>(__TAURI_INVOKE("git_ahead_behind", { projectId })),
	gitRemotes: (projectId: ProjectId) => typedError<GitRemote[], AppError>(__TAURI_INVOKE("git_remotes", { projectId })),
	gitGutter: (projectId: ProjectId, path: string) => typedError<GutterHunk[], AppError>(__TAURI_INVOKE("git_gutter", { projectId, path })),
	gitBlameRange: (projectId: ProjectId, path: string, from: number, to: number) => typedError<BlameLine[], AppError>(__TAURI_INVOKE("git_blame_range", { projectId, path, from, to })),
	gitStage: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_stage", { projectId, paths })),
	gitUnstage: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_unstage", { projectId, paths })),
	gitDiscard: (projectId: ProjectId, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("git_discard", { projectId, paths })),
	gitCommit: (projectId: ProjectId, message: string, opts: CommitOptions) => typedError<string, AppError>(__TAURI_INVOKE("git_commit", { projectId, message, opts })),
	gitPush: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_push", { projectId })),
	gitPull: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_pull", { projectId })),
	gitFetch: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_fetch", { projectId })),
	gitUndoLastCommit: (projectId: ProjectId) => typedError<null, AppError>(__TAURI_INVOKE("git_undo_last_commit", { projectId })),
	gitCurrentUser: (projectId: ProjectId) => typedError<string | null, AppError>(__TAURI_INVOKE("git_current_user", { projectId })),
	ptyDefaultOptions: (projectId: ProjectId) => typedError<PtySpawnOptions, AppError>(__TAURI_INVOKE("pty_default_options", { projectId })),
	ptyWrite: (sessionId: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("pty_write", { sessionId, data })),
	ptyResize: (sessionId: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("pty_resize", { sessionId, cols, rows })),
	ptyKill: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("pty_kill", { sessionId })),
	ptySetPaused: (sessionId: string, paused: boolean) => typedError<null, AppError>(__TAURI_INVOKE("pty_set_paused", { sessionId, paused })),
	terminalSessions: (projectId: ProjectId) => typedError<TerminalSession[], AppError>(__TAURI_INVOKE("terminal_sessions", { projectId })),
	shellProfiles: () => typedError<ShellProfile[], AppError>(__TAURI_INVOKE("shell_profiles")),
	resolveTerminalPath: (path: string, cwd: string) => typedError<string, AppError>(__TAURI_INVOKE("resolve_terminal_path", { path, cwd })),
	localeList: () => typedError<LocaleSummary[], AppError>(__TAURI_INVOKE("locale_list")),
	localeGet: (localeId: string) => typedError<ResolvedLocale_Serialize, AppError>(__TAURI_INVOKE("locale_get", { localeId })),
	localeGetCurrent: (systemLanguage: string) => typedError<ResolvedLocale_Serialize, AppError>(__TAURI_INVOKE("locale_get_current", { systemLanguage })),
	themeList: () => typedError<ThemeSummary[], AppError>(__TAURI_INVOKE("theme_list")),
	themeGet: (themeId: string) => typedError<ResolvedTheme, AppError>(__TAURI_INVOKE("theme_get", { themeId })),
	themeGetCurrent: () => typedError<ResolvedTheme, AppError>(__TAURI_INVOKE("theme_get_current")),
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	settingsUpdate: (patch: SettingsPatch) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_update", { patch })),
	settingsSetTheme: (themeId: string) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set_theme", { themeId })),
};

/** Events */
export const events = {
	agentExternalOpen: makeEvent<AgentExternalOpen>("agent:external-open"),
	agentStateChanged: makeEvent<AgentStateChanged>("agent:state-changed"),
	appReady: makeEvent<AppReady>("app:ready"),
	fsChanged: makeEvent<FsChanged>("fs:changed"),
	gitRefsChanged: makeEvent<GitRefsChanged>("git:refs-changed"),
	gitStatusChanged: makeEvent<GitStatusChanged>("git:status-changed"),
	layoutChanged: makeEvent<LayoutChanged>("layout:changed"),
	lspSessionStatusChanged: makeEvent<LspSessionStatusChanged>("lsp:session-status-changed"),
	projectActivated: makeEvent<ProjectActivated>("project:activated"),
	projectClosed: makeEvent<ProjectClosed>("project:closed"),
	projectFocusKindChanged: makeEvent<ProjectFocusKindChanged>("project:focus-kind-changed"),
	projectListChanged: makeEvent<ProjectListChanged>("project:list-changed"),
	projectOpened: makeEvent<ProjectOpened>("project:opened"),
	terminalCwdChanged: makeEvent<TerminalCwdChanged>("terminal:cwd-changed"),
	terminalExited: makeEvent<TerminalExited>("terminal:exited"),
	themeChanged: makeEvent<ThemeChanged>("theme:changed"),
};

/* Types */
export type AgentExternalOpen = {
	request: ExternalOpenRequest,
};

export type AgentStateChanged = {
	projectId: ProjectId,
	agents: DetectedAgent[],
};

export type AheadBehind = {
	ahead: number,
	behind: number,
};

export type AppError = { code: "Io"; message: string } | { code: "NotFound"; message: string } | { code: "InvalidArgument"; message: string } | { code: "Internal"; message: string };

export type AppInfo = {
	name: string,
	version: string,
	platform: string,
	arch: string,
};

export type AppReady = {
	version: string,
};

export type BlameLine = {
	line: number,
	commitId: string,
	author: string,
	timeUnix: number | null,
	summary: string,
	isUncommitted: boolean,
};

export type CapabilityKind = "git" | "lsp" | "terminal" | "agentWatch";

export type CliInstallStatus = {
	installed: boolean,
	resolvedPath?: string | null,
	targetPath: string,
	editorEnvHint: string,
};

export type ClosedTab = {
	tab: Tab,
	paneId: PaneId,
	index: number,
};

export type CommitOptions = {
	amend?: boolean,
	stageAll?: boolean,
};

export type DetectedAgent = {
	sessionId: string,
	name: string,
	pid: number,
};

export type DiffMode = "workdirVsIndex" | "indexVsHead";

export type DiffSides = {
	original: string,
	modified: string,
	languageId: string,
};

export type DropEdge = "left" | "right" | "top" | "bottom" | "center";

export type ExternalOpenRequest = {
	path: string,
	waitMarker?: string | null,
};

export type FileSizeTier = "normal" | "large" | "readOnly" | "refused";

export type FocusKind = "file" | "terminal" | "settings" | "diff" | "welcome";

export type FsChange = {
	kind: FsChangeKind,
	paths: string[],
	fromApp: boolean,
};

export type FsChangeKind = "created" | "modified" | "removed" | "renamed";

export type FsChanged = {
	projectId: ProjectId,
	change: FsChange,
};

export type GitChangeKind = "modified" | "added" | "deleted" | "renamed" | "untracked" | "typeChange" | "conflicted";

export type GitRefsChanged = {
	projectId: ProjectId,
};

export type GitRemote = {
	name: string,
	url: string,
};

export type GitStatus = {
	rows: StatusRow[],
	branch: string | null,
	ahead: number,
	behind: number,
	hasRemote: boolean,
};

export type GitStatusChanged = {
	projectId: ProjectId,
};

export type GutterHunk = {
	kind: HunkKind,
	start: number,
	end: number,
};

export type HunkKind = "added" | "modified" | "deleted";

export type LayoutChanged = {
	projectId: ProjectId,
	revision: number,
};

export type LoadedPlugin = {
	manifest: PluginManifest,
	root: string,
	enabled: boolean,
	error?: string | null,
};

export type LocaleSummary = {
	id: string,
	name: string,
	builtin: boolean,
};

export type LogEntry = {
	id: string,
	parents: string[],
	summary: string,
	author: string,
	timeUnix: number | null,
	refs: string[],
};

export type LspServerDetection = {
	id: LspServerId,
	name: string,
	resolvedPath?: string | null,
	available: boolean,
	installHint?: string | null,
};

export type LspServerId = "vtsls" | "rustAnalyzer" | "basedPyright" | "ruff" | "marksman";

export type LspSessionInfo = {
	sessionId: string,
	projectId: ProjectId,
	serverId: LspServerId,
	root: string,
	status: LspSessionStatus,
	lastError?: string | null,
};

export type LspSessionStatus = "starting" | "running" | "crashed" | "stopped";

export type LspSessionStatusChanged = {
	sessionId: string,
	status: LspSessionStatus,
	lastError: string | null,
};

export type OpenedFile = {
	path: string,
	content: string,
	languageId: string,
	byteSize: number,
	lineCount: number,
	tier: FileSizeTier,
	readOnly: boolean,
	modifiedMs: number | null,
};

export type PaneId = string;

export type PaneNode = { node: "split"; id: PaneId; dir: SplitDir; children: PaneNode[]; sizes: (number | null)[] } | { node: "leaf"; id: PaneId; tabs: Tab[]; active: TabId | null };

export type PluginContributions = {
	languages?: PluginLanguageContribution[],
	lsp?: PluginLspContribution[],
	themes?: PluginThemeContribution[],
};

export type PluginLanguageContribution = {
	id: string,
	extensions: string[],
	aliases?: string[],
	grammar?: string | null,
};

export type PluginLspContribution = {
	languageId: string,
	id: string,
	cmd: string,
	args?: string[],
	detect?: string[],
	shareable?: boolean,
	installInstructions?: string | null,
};

export type PluginManifest = {
	manifestVersion: number,
	id: string,
	name: string,
	version: string,
	contributes?: PluginContributions,
};

export type PluginThemeContribution = {
	id: string,
	path: string,
};

export type Project = {
	id: ProjectId,
	root: string,
	name: string,
	capabilities?: CapabilityKind[],
	rootMissing?: boolean,
};

export type ProjectActivated = {
	projectId: ProjectId | null,
};

export type ProjectAgents = {
	projectId: ProjectId,
	agents: DetectedAgent[],
};

export type ProjectClosed = {
	projectId: ProjectId,
};

export type ProjectFocusKindChanged = {
	projectId: ProjectId,
	kind: FocusKind,
};

export type ProjectId = string;

export type ProjectLayout = {
	version: number,
	root: PaneNode,
	focusedPane: PaneId,
	revision?: number,
	closedTabs?: ClosedTab[],
};

export type ProjectListChanged = {
	projects: ProjectRef[],
};

export type ProjectOpenResult = {
	project: Project,
	alreadyOpen: boolean,
};

export type ProjectOpened = {
	project: Project,
};

export type ProjectRef = {
	id: ProjectId,
	root: string,
	name: string,
};

export type PtySpawnOptions = {
	projectId: ProjectId,
	cwd: string,
	shell?: string | null,
	cols: number,
	rows: number,
};

export type ResolvedLocale = ResolvedLocale_Serialize | ResolvedLocale_Deserialize;

export type ResolvedLocale_Deserialize = {
	id: string,
	name: string,
	messages: { [key in string]: string },
	warnings?: string[],
};

export type ResolvedLocale_Serialize = {
	id: string,
	name: string,
	messages: { [key in string]: string },
	warnings?: string[],
};

export type ResolvedTheme = {
	id: string,
	name: string,
	type: ThemeType,
	colors: { [key in string]: string },
	syntax: { [key in string]: SyntaxStyle },
	terminal: { [key in string]: string },
	warnings?: string[],
};

export type SearchMatch = {
	path: string,
	line: number,
	column: number,
	preview: string,
	matchStart: number,
	matchEnd: number,
};

export type SearchQuery = {
	text: string,
	caseSensitive?: boolean,
	wholeWord?: boolean,
	regex?: boolean,
	includeGlob?: string | null,
	excludeGlob?: string | null,
};

export type Settings = {
	version: number,
	themeId?: string,
	editorFontSize?: number,
	terminalFontSize?: number,
	shellOverride?: string | null,
	followSystemTheme?: boolean,
	language?: string,
	toastPosition?: string,
	resizerThickness?: number,
};

export type SettingsPatch = {
	themeId: string | null,
	editorFontSize: number | null,
	terminalFontSize: number | null,
	shellOverride: string | null,
	followSystemTheme: boolean | null,
	language: string | null,
	toastPosition: string | null,
	resizerThickness: number | null,
};

export type ShellProfile = {
	id: string,
	name: string,
	path: string,
	args?: string[],
};

export type SplitDir = "horizontal" | "vertical";

export type StatusRow = {
	path: string,
	origPath?: string | null,
	staged?: GitChangeKind | null,
	unstaged?: GitChangeKind | null,
	isConflicted: boolean,
};

export type SyntaxStyle = {
	fg: string,
	bold?: boolean,
	italic?: boolean,
};

export type Tab = {
	id: TabId,
	kind: TabKind,
	title: string,
	pinned?: boolean,
	preview?: boolean,
	dirty?: boolean,
	viewState?: string | null,
};

export type TabId = string;

export type TabKind = { kind: "file"; path: string } | { kind: "terminal"; sessionId: string } | { kind: "settings" } | { kind: "diff"; path: string; staged: boolean } | { kind: "welcome" };

export type TerminalCwdChanged = {
	sessionId: string,
	cwd: string,
};

export type TerminalExited = {
	sessionId: string,
	code: number | null,
};

export type TerminalSession = {
	id: string,
	projectId: ProjectId,
	cwd: string,
	shell: string,
	running: boolean,
};

export type ThemeChanged = {
	themeId: string,
};

export type ThemeSummary = {
	id: string,
	name: string,
	type: ThemeType,
	builtin: boolean,
};

export type ThemeType = "dark" | "light";

export type TreeEntryKind = "file" | "directory";

export type TreeRow = {
	path: string,
	name: string,
	kind: TreeEntryKind,
	depth: number,
	expanded: boolean,
	hasChildren: boolean,
};

export type TreeRowPage = {
	rows: TreeRow[],
	total: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

